module

public import AISafetyAtlas.Compositional.Hyperproperties

/-!
# The observation topology on systems

`AISafetyAtlas.Compositional.Hyperproperties` proves a decomposition theorem for
an *arbitrary* topology on systems, and deliberately declines to read it as
hypersafety and hyperliveness.  This module supplies the topology that makes
that reading correct.

## Why the topology is a `def`, not an `instance`

Everything here depends on the observation relation `prefixOf`, and on the
prefix type.  A global `TopologicalSpace (TraceSystem Trace)` instance cannot
mention either, so registering one would silently forget the observation
semantics and let an unrelated topology be substituted under the same theorem
names.  `prefixTopology` is therefore a plain definition, installed locally with
`letI` at each use.

## What is proved

* `isOpen_cone`: the cones `{S | S realizes M}` are open, and they are the local
  basis by construction.
* `isClosed_iff_hyperSafety`: closed sets are exactly the operationally
  hypersafety hyperproperties of Clarkson and Schneider, those whose every
  violation has a finite bad observation.
* `dense_iff_hyperLiveness`: dense sets are exactly the operationally
  hyperliveness ones, those meeting every realizable finite observation.
* `hyperSafety_of_isKSafety`: every `k`-safety hyperproperty is hypersafety, the
  inclusion that joins this module to the `k`-safety reduction.
* `hyperSafety_hyperLiveness_decomposition`: the generic decomposition,
  specialized through this topology, so the operational reading is now earned
  rather than asserted.

Sources: Clarkson and Schneider, *Hyperproperties*, JCS 18(6), 2010; Alpern and
Schneider, *Defining liveness*, IPL 21(4), 1985, for the trace-level pattern.
-/

namespace AISafetyAtlas.Compositional.Hyperproperties

variable {Prefix Trace : Type*}

/-- The set of systems realizing a finite observation. -/
@[expose] public def Cone (prefixOf : Prefix → Trace → Prop)
    (M : Observation Prefix) : Set (TraceSystem Trace) :=
  {S | Realizes prefixOf M S}

/-- Realizing a union of observations is realizing both. -/
public theorem cone_union (prefixOf : Prefix → Trace → Prop)
    [DecidableEq Prefix] (M N : Observation Prefix) :
    Cone prefixOf (M ∪ N) = Cone prefixOf M ∩ Cone prefixOf N := by
  ext S
  constructor
  · intro h
    exact ⟨fun p hp => h p (Finset.mem_union_left _ hp),
      fun p hp => h p (Finset.mem_union_right _ hp)⟩
  · rintro ⟨h₁, h₂⟩ p hp
    rcases Finset.mem_union.mp hp with hp' | hp'
    · exact h₁ p hp'
    · exact h₂ p hp'

/-- Every system realizes the empty observation. -/
public theorem cone_empty (prefixOf : Prefix → Trace → Prop) :
    Cone prefixOf (∅ : Observation Prefix) = Set.univ := by
  ext S
  simp [Cone, Realizes]

/--
The observation topology on systems, parameterized by the observation relation.

A set of systems is open when every member is separated from the outside by a
finite observation it realizes.  This is the local-basis presentation of the
topology generated by the cones; stating it directly avoids any dependence on
basis machinery.
-/
@[expose, reducible] public def prefixTopology [DecidableEq Prefix]
    (prefixOf : Prefix → Trace → Prop) : TopologicalSpace (TraceSystem Trace) where
  IsOpen U := ∀ S ∈ U, ∃ M : Observation Prefix,
    Realizes prefixOf M S ∧ Cone prefixOf M ⊆ U
  isOpen_univ := by
    intro S _
    exact ⟨∅, by simp [Realizes], by simp⟩
  isOpen_inter := by
    rintro U V hU hV S ⟨hSU, hSV⟩
    obtain ⟨M, hM, hMU⟩ := hU S hSU
    obtain ⟨N, hN, hNV⟩ := hV S hSV
    refine ⟨M ∪ N, ?_, ?_⟩
    · intro p hp
      rcases Finset.mem_union.mp hp with hp' | hp'
      · exact hM p hp'
      · exact hN p hp'
    · rw [cone_union]
      exact Set.inter_subset_inter hMU hNV
  isOpen_sUnion := by
    intro 𝒮 h S hS
    obtain ⟨U, hU𝒮, hSU⟩ := hS
    obtain ⟨M, hM, hMU⟩ := h U hU𝒮 S hSU
    exact ⟨M, hM, hMU.trans (Set.subset_sUnion_of_mem hU𝒮)⟩

section

variable [DecidableEq Prefix] (prefixOf : Prefix → Trace → Prop)

/-- Cones are open: each cone is its own separating observation. -/
public theorem isOpen_cone (M : Observation Prefix) :
    @IsOpen _ (prefixTopology prefixOf) (Cone prefixOf M) :=
  fun _ hS => ⟨M, hS, subset_rfl⟩

/-!
### Operational hypersafety and hyperliveness

These are the Clarkson-Schneider definitions, stated without reference to any
topology, so that the theorems below are genuine characterizations rather than
renamings.
-/

/-- **Operational hypersafety.**  Every violation is witnessed by a finite bad
observation that the violating system realizes. -/
@[expose] public def IsHyperSafetyOp (H : Hyperproperty Trace) : Prop :=
  ∀ S, S ∉ H → ∃ M : Observation Prefix,
    Realizes prefixOf M S ∧ IsBadObservation prefixOf H M

/-- **Operational hyperliveness.**  Every finite observation that some system
realizes is also realized by a system satisfying `H`. -/
@[expose] public def IsHyperLivenessOp (H : Hyperproperty Trace) : Prop :=
  ∀ M : Observation Prefix, (∃ S, Realizes prefixOf M S) →
    ∃ S ∈ H, Realizes prefixOf M S

/--
**Hypersafety is closedness.**

In the observation topology, a hyperproperty is closed exactly when every
violating system exhibits a finite bad observation.
-/
public theorem isClosed_iff_hyperSafety (H : Hyperproperty Trace) :
    @IsClosed _ (prefixTopology prefixOf) H ↔ IsHyperSafetyOp prefixOf H := by
  let : TopologicalSpace (TraceSystem Trace) := prefixTopology prefixOf
  rw [← isOpen_compl_iff]
  constructor
  · intro hopen S hS
    obtain ⟨M, hM, hsub⟩ := hopen S hS
    exact ⟨M, hM, fun S' hS' => hsub hS'⟩
  · intro hsafe S hS
    obtain ⟨M, hM, hbad⟩ := hsafe S hS
    exact ⟨M, hM, fun S' hS' => hbad S' hS'⟩

/--
**Hyperliveness is density.**

In the observation topology, a hyperproperty is dense exactly when every
realizable finite observation is realized by some system satisfying it.
-/
public theorem dense_iff_hyperLiveness (H : Hyperproperty Trace) :
    @Dense _ (prefixTopology prefixOf) H ↔ IsHyperLivenessOp prefixOf H := by
  let : TopologicalSpace (TraceSystem Trace) := prefixTopology prefixOf
  rw [dense_iff_inter_open]
  constructor
  · intro hdense M hM
    obtain ⟨S₀, hS₀⟩ := hM
    obtain ⟨S, hSmem, hSH⟩ :=
      hdense (Cone prefixOf M) (isOpen_cone prefixOf M) ⟨S₀, hS₀⟩
    exact ⟨S, hSH, hSmem⟩
  · intro hlive U hU hne
    obtain ⟨S, hS⟩ := hne
    obtain ⟨M, hM, hsub⟩ := hU S hS
    obtain ⟨S', hS'H, hS'M⟩ := hlive M ⟨S, hM⟩
    exact ⟨S', hsub hS'M, hS'H⟩

omit [DecidableEq Prefix] in
/--
**Every `k`-safety hyperproperty is hypersafety.**

This is the inclusion that connects the `k`-safety reduction in the parent
module to the topological decomposition here: `IsKSafety` additionally bounds
the witness size by `k`, which hypersafety does not require.
-/
public theorem hyperSafety_of_isKSafety {k : ℕ} {H : Hyperproperty Trace}
    (hk : IsKSafety prefixOf k H) : IsHyperSafetyOp prefixOf H := by
  intro S hS
  obtain ⟨M, _, hreal, hbad⟩ := hk S hS
  exact ⟨M, hreal, hbad⟩

/--
**Alpern-Schneider decomposition, through the observation topology.**

Every hyperproperty is the intersection of an operationally hypersafety part and
an operationally hyperliveness part.

Unlike `hypersafety_hyperliveness_decomposition` in the parent module, the two
parts here carry their Clarkson-Schneider meanings rather than the meanings of
`IsClosed` and `Dense` at an unspecified topology.
-/
public theorem hyperSafety_hyperLiveness_decomposition (H : Hyperproperty Trace) :
    ∃ safetyPart livenessPart : Hyperproperty Trace,
      IsHyperSafetyOp prefixOf safetyPart ∧
        IsHyperLivenessOp prefixOf livenessPart ∧
        H = safetyPart ∩ livenessPart := by
  let : TopologicalSpace (TraceSystem Trace) := prefixTopology prefixOf
  obtain ⟨C, D, hC, hD, hCD⟩ := topological_decomposition H
  refine ⟨C, D, ?_, ?_, hCD⟩
  · exact (isClosed_iff_hyperSafety prefixOf C).mp hC
  · exact (dense_iff_hyperLiveness prefixOf D).mp hD

end

end AISafetyAtlas.Compositional.Hyperproperties
