#!/usr/bin/env python3
"""Pin the public declaration names of the facade closure.

The atlas describes itself as an etalon: other work is supposed to be measured
against these theorems, and downstream code names them.  Under that claim a
rename is not a refactor, it is a breaking change to a standard — and nothing in
the gate noticed one.  ``check_print_axioms.py`` re-derives the closure on every
run, so a declaration that vanished simply stopped being scanned, silently.

This is the job ``checkdecls`` does for Mathlib-adjacent projects.  It is not
adopted here because it arrives only as a transitive package of ``doc-gen4``,
and depending on a tool the dependency graph could drop at any time is exactly
the reproducibility rot the ledger exists to prevent.  The check itself is a
sorted list and a diff.

The pinned list is generated, not hand-maintained: run with ``--write`` after a
deliberate rename, and the diff shows up in review as an explicit line rather
than as an absence.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from check_print_axioms import (  # noqa: E402
    PUBLIC_THEOREM_RE,
    facade_sources,
)

ROOT = Path(__file__).resolve().parents[1]
PINNED = ROOT / "docs" / "status" / "public-api.txt"

HEADER = (
    "# Generated by scripts/check_public_api.py --write; do not edit directly.\n"
    "#\n"
    "# Every public theorem and lemma reachable through the AISafetyAtlas root\n"
    "# import. These are the names downstream work is entitled to depend on.\n"
    "# Removing or renaming one is a breaking change and must show up here as a\n"
    "# deleted line, not as a silent absence.\n"
)


def public_names() -> list[str]:
    names: set[str] = set()
    for path in facade_sources():
        module = ".".join(path.relative_to(ROOT).with_suffix("").parts)
        for line in path.read_text(encoding="utf-8").splitlines():
            if match := PUBLIC_THEOREM_RE.match(line):
                names.add(f"{module}::{match.group(1)}")
    return sorted(names)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate the pinned list after a deliberate rename",
    )
    args = parser.parse_args()

    current = public_names()
    body = HEADER + "".join(f"{name}\n" for name in current)

    if args.write:
        PINNED.parent.mkdir(parents=True, exist_ok=True)
        PINNED.write_text(body, encoding="utf-8")
        print(f"public api pinned: {len(current)} declarations written to {PINNED}")
        return 0

    if not PINNED.is_file():
        print(
            f"public api error: {PINNED} is missing; run "
            "scripts/check_public_api.py --write",
            file=sys.stderr,
        )
        return 1

    pinned = [
        line
        for line in PINNED.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    removed = sorted(set(pinned) - set(current))
    added = sorted(set(current) - set(pinned))
    if removed or added:
        for name in removed:
            print(f"public api error: {name} disappeared from the facade", file=sys.stderr)
        for name in added:
            print(f"public api error: {name} is new and unpinned", file=sys.stderr)
        print(
            "public api error: run scripts/check_public_api.py --write to accept "
            "these changes deliberately",
            file=sys.stderr,
        )
        return 1

    print(f"public api ok: {len(current)} pinned declarations unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
