#!/usr/bin/env python3
"""Pin the public declaration names of the facade closure.

The atlas describes itself as an etalon: other work is supposed to be measured
against these theorems, and downstream code names them.  Under that claim a
rename is not a refactor, it is a breaking change to a standard — and nothing in
the gate noticed one.  ``check_print_axioms.py`` re-derives the closure on every
run, so a declaration that vanished simply stopped being scanned, silently.

This is the job ``checkdecls`` does for Mathlib-adjacent projects.  It is not
adopted here because it arrives only as a transitive package of ``doc-gen4``,
and depending on a tool the dependency graph could drop at any time is exactly
the reproducibility rot the ledger exists to prevent.  The check itself is a
sorted list and a diff.

The pinned list is generated, not hand-maintained: run with ``--write`` after a
deliberate rename, and the diff shows up in review as an explicit line rather
than as an absence.
"""

from __future__ import annotations

import argparse
import re
import collections
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from check_print_axioms import (  # noqa: E402
    PUBLIC_THEOREM_RE,
    facade_sources,
)

ROOT = Path(__file__).resolve().parents[1]
PINNED = ROOT / "docs" / "status" / "public-api.txt"

HEADER = (
    "# Generated by scripts/check_public_api.py --write; do not edit directly.\n"
    "#\n"
    "# Every public theorem and lemma reachable through the AISafetyAtlas root\n"
    "# import, EXCEPT those under AISafetyAtlas/Examples/. These are the names\n"
    "# downstream work is entitled to depend on. Removing or renaming one is a\n"
    "# breaking change and must show up here as a deleted line, not as a silent\n"
    "# absence.\n"
    "#\n"
    "# Examples are excluded because a worked witness is evidence that a theorem\n"
    "# is not vacuous, not an interface anyone should build on. Pinning them made\n"
    "# a third of this file one-off instances -- 1,049 of 3,262 before the change,\n"
    "# 485 of them added by a single campaign -- which is not the 'small stable\n"
    "# facade' lean-public-api.md asks for, and committed the project to never\n"
    "# renaming a witness. They are still built, still checked for axioms, and\n"
    "# still the thing check_witness_debt reads; they are simply not promises.\n"
)

# Worked witnesses under this directory ground library theorems; they are not
# API. `check_witness_debt` already excludes them from its pinned surface, so
# dropping them here does not move the witness-debt denominator.
EXAMPLES_DIR = "AISafetyAtlas.Examples."


NAMESPACE_RE = re.compile(r"^namespace\s+([A-Za-z_][\w.'\u2080-\u2089]*)")
END_RE = re.compile(r"^end(?:\s+([A-Za-z_][\w.'\u2080-\u2089]*))?\s*$")


def public_names() -> list[str]:
    """Pinned names, qualified by namespace only where a leaf is ambiguous.

    The pin is a *textual* scan, and until 2026-09-22 it recorded a theorem's
    leaf name with the enclosing `namespace` thrown away. That is lossless only
    while no two theorems in one module share a leaf, and
    `AISafetyAtlas.Wireheading.RewardGrid` has two: `GridEnv.complement_involutive`
    and `FullEnv.complement_involutive`. Both collapsed to the same pin line, so
    `check_witness_debt` -- which resolves a pin against the elaborated index --
    found two candidates for it and refused, every run, in a warning nobody
    could act on because the pin held no way to tell them apart.

    Leaves stay bare, so the pin does not churn; only an ambiguous one gains its
    namespace. A check that silently declines to check something is the species
    this file exists to prevent.
    """
    names: set[str] = set()
    for path in facade_sources():
        module = ".".join(path.relative_to(ROOT).with_suffix("").parts)
        if module.startswith(EXAMPLES_DIR):
            continue
        stack: list[str] = []
        found: list[tuple[str, str]] = []
        for line in path.read_text(encoding="utf-8").splitlines():
            if match := NAMESPACE_RE.match(line):
                stack.append(match.group(1))
                continue
            if match := END_RE.match(line):
                closing = match.group(1)
                if closing is None:
                    pass
                elif stack and stack[-1] == closing:
                    stack.pop()
                elif closing in stack:
                    del stack[stack.index(closing):]
                continue
            if match := PUBLIC_THEOREM_RE.match(line):
                leaf = match.group(1)
                # The innermost open namespace, and only that one: the outer
                # levels are the module's own namespace and adding them would
                # spell a name no consumer writes.
                inner = stack[-1] if stack else ""
                found.append((leaf, inner))
        # Count by the *final* component. One of the two `RewardGrid` theorems
        # is written `FullEnv.complement_involutive` in the source and the other
        # is a bare `complement_involutive` inside `namespace GridEnv`, so
        # counting the captured text would call them distinct and disambiguate
        # neither.
        counts = collections.Counter(leaf.rsplit(".", 1)[-1] for leaf, _ in found)
        for leaf, inner in found:
            # A name the source already qualified is left exactly as written;
            # only a bare, ambiguous leaf gains the namespace it was declared in.
            needs = counts[leaf.rsplit(".", 1)[-1]] > 1 and "." not in leaf and inner
            names.add(f"{module}::{inner}.{leaf}" if needs else f"{module}::{leaf}")
    return sorted(names)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate the pinned list after a deliberate rename",
    )
    args = parser.parse_args()

    current = public_names()
    body = HEADER + "".join(f"{name}\n" for name in current)

    if args.write:
        PINNED.parent.mkdir(parents=True, exist_ok=True)
        PINNED.write_text(body, encoding="utf-8")
        print(f"public api pinned: {len(current)} declarations written to {PINNED}")
        return 0

    if not PINNED.is_file():
        print(
            f"public api error: {PINNED} is missing; run "
            "scripts/check_public_api.py --write",
            file=sys.stderr,
        )
        return 1

    pinned = [
        line
        for line in PINNED.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    removed = sorted(set(pinned) - set(current))
    added = sorted(set(current) - set(pinned))
    if removed or added:
        for name in removed:
            print(f"public api error: {name} disappeared from the facade", file=sys.stderr)
        for name in added:
            print(f"public api error: {name} is new and unpinned", file=sys.stderr)
        print(
            "public api error: run scripts/check_public_api.py --write to accept "
            "these changes deliberately",
            file=sys.stderr,
        )
        return 1

    print(f"public api ok: {len(current)} pinned declarations unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
