#!/usr/bin/env python3
"""Enforce the Examples layout rule so nobody has to learn it.

`AGENTS.md` § Examples layout rule states it; this decides it. The rule is
arbitrary-looking from outside — which is exactly why a newcomer gets it wrong
and why it should be a check rather than something to read.

Three shapes are legal under `AISafetyAtlas/Examples/`:

* **Mirror** — `Examples/P.lean` where `AISafetyAtlas/P.lean` exists. Its
  namespace repeats its own path: `Examples/Verification/Robot.lean` declares
  `AISafetyAtlas.Examples.Verification.Robot`. A top-level facade mirrors flat,
  which is why `Examples/SelfAwareness.lean` is a mirror and not a harness.
* **Scenario** — a file inside a mirror *directory* with no module of its own,
  such as `Examples/Oversight/JointObservation/Procurement.lean`. Legal because
  the directory mirrors one; the file need not.
* **Harness** — serves no single module and stays flat in `Examples/`. The set
  is closed and listed below; a new one is a decision, not a default, so adding
  to `HARNESSES` should be deliberate.

Namespace agreement is checked for every file regardless of shape: a file whose
namespace does not match its path is unfindable from the module it witnesses,
which defeats the point of the mirror convention.

**Two spellings are accepted, because the tree uses both.** `AGENTS.md` prints
the full-path form (`Examples/Verification/Robot.lean` in
`AISafetyAtlas.Examples.Verification.Robot`) and 47 files follow it; 21 use the
directory form (`AISafetyAtlas.Examples.Verification`), which is equally
findable. Accepting both is a deliberate choice not to mass-rename 21 files to
satisfy a check written after them. What is rejected is a namespace that agrees
with neither, because that one really is unfindable.

**Generated files are skipped**, by marker rather than by name: a file a script
produces declares nothing and carries no namespace, so a namespace rule over it
is meaningless, and naming the one that exists today would be a debt that the
next generated example silently escapes.

There is no exception list. The two files that would have needed one were
resolved instead — `Registry.lean` by the generated-file rule above, and
`Inference/Enumerable.lean` by being renamed to the namespace it already
declared. A rule with an exception list is one a contributor has to argue with;
this one they can only obey.

Exit 0 when the tree is legal, 1 otherwise. Part of the cheap gate.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIB = ROOT / "AISafetyAtlas"
EXAMPLES = LIB / "Examples"

# Flat files that witness no single module. Closed set: see the module docstring.
HARNESSES = {
    "FirstContribution",
    "HaltingExample",
    "NFLConcrete",
    "NonVacuity",
    "PublicAPI",
    "Registry",
    "SixTargets",
    "WorkbenchConsumers",
}

# A file some script writes. It declares nothing, so it has no namespace to
# agree with anything, and editing it by hand is already a gate failure.
GENERATED_RE = re.compile(r"Generated by `?scripts/|do not edit directly",
                          re.IGNORECASE)

NAMESPACE_RE = re.compile(r"^namespace\s+(\S+)", re.MULTILINE)


def accepted_namespaces(relative: Path) -> tuple[str, str]:
    """The full-path spelling and the directory spelling, in that order."""
    parts = list(relative.with_suffix("").parts)
    full = ".".join(["AISafetyAtlas", "Examples", *parts])
    directory = ".".join(["AISafetyAtlas", "Examples", *parts[:-1]])
    return full, directory


def main() -> int:
    if not EXAMPLES.is_dir():
        print(f"check_examples_layout: missing {EXAMPLES}", file=sys.stderr)
        return 1

    problems: list[str] = []
    checked = 0
    generated = 0

    for path in sorted(EXAMPLES.rglob("*.lean")):
        relative = path.relative_to(EXAMPLES)
        checked += 1

        # --- placement ---------------------------------------------------
        mirrors_module = (LIB / relative).is_file()
        if not mirrors_module:
            if len(relative.parts) == 1:
                if relative.stem not in HARNESSES:
                    problems.append(
                        f"{path.relative_to(ROOT)}: flat file that mirrors no "
                        f"module and is not a named harness. Either put it at "
                        f"AISafetyAtlas/Examples/{relative.stem}/... beside the "
                        f"module it witnesses, or add it to HARNESSES here with "
                        f"a reason — see AGENTS.md § Examples layout rule."
                    )
            elif not (LIB / relative.parent).is_dir():
                problems.append(
                    f"{path.relative_to(ROOT)}: nested under "
                    f"Examples/{relative.parent}, which mirrors no module "
                    f"directory. A scenario file is legal only inside a mirror "
                    f"directory — see AGENTS.md § Examples layout rule."
                )

        # --- namespace agreement -----------------------------------------
        text = path.read_text(encoding="utf-8", errors="replace")
        if GENERATED_RE.search(text):
            generated += 1
            continue

        accepted = accepted_namespaces(relative)
        found = NAMESPACE_RE.search(text)
        if found is None:
            problems.append(
                f"{path.relative_to(ROOT)}: declares no namespace; expected "
                f"`namespace {accepted[0]}`."
            )
        elif found.group(1) not in accepted:
            problems.append(
                f"{path.relative_to(ROOT)}: declares `{found.group(1)}`, which "
                f"is neither `{accepted[0]}` nor `{accepted[1]}`. One of those "
                f"two — otherwise the witness cannot be found from the module "
                f"it witnesses. See AGENTS.md § Examples layout rule."
            )

    if problems:
        print(f"check_examples_layout: {len(problems)} problem(s) "
              f"in {checked} example file(s)", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1

    print(f"check_examples_layout ok: {checked} example files, "
          f"{len(HARNESSES)} harnesses, {generated} generated (skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
