#!/usr/bin/env python3
"""Every Lean declaration a MAIS grading artifact names must exist.

A ledger row's ``resolution`` is read as a pointer: *this* is the theorem that
settled the row, go and check it.  A pointer to a name the tree does not carry
is worse than no pointer, because it reads as verified and cannot be followed.

Two got through before this check existed.  ``CONJ-009.resolution`` named
``behaviorEq_of_directionDifference_eq_zero`` for the same-direction half of its
equivalence; the lemma is ``behaviorEq_of_childDifference_eq_zero`` and the
cited name never existed at all.  ``docs/provenance/mais-o24-statability.md``
named ``gapBox`` and ``gap_mem_gapBox``, which were real once and were replaced
by ``utilityBox`` and ``utility_mem_utilityBox`` in the pass the same bullet
claimed to be describing.  Neither is visible to any other validator: prose that
names a nonexistent theorem is well formed on both sides.

The scan is deliberately narrow.  It reads the artifacts that carry *grades* --
the ledger and the MAIS provenance notes -- rather than every document in the
tree, because those are where a wrong name is read as a verified claim.  It
matches only tokens that look like Lean declaration names and are not in the
vocabulary lists below, so ``source_note`` (a ledger field) and ``C_j`` (print's
notation) do not trip it.

**This check is only as current as the declaration index**, and the cheap gate
builds no Lean, so a stale ``declaration-index.json`` makes it answer about a
tree that no longer exists -- passing over a name deleted since the last build,
or failing on one added since. The index is regenerated by
``scripts/generate_declaration_index.py --write`` after
``xargs lake build < scripts/lean_build_targets.txt``; everything under
``AISafetyAtlas/Conjectures`` is off the root import, so a root build alone does
not refresh it.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "docs" / "status" / "declaration-index.json"

# Grading artifacts: a name here is read as "go and check this".
SCANNED = [
    ROOT / "conjectures.yaml",
    ROOT / "docs" / "provenance" / "mais-a2-statement-coverage.md",
    ROOT / "docs" / "provenance" / "mais-conjecture-source-vs-lean.md",
    ROOT / "docs" / "provenance" / "mais-o24-statability.md",
    ROOT / "docs" / "guide" / "conjectures.md",
    # STATE.md carries grading claims too, and proved it on 2026-08-23 by
    # asserting MAIS-O29(b) was retracted a day after a bound at print's own
    # quantifier landed. A summary that names theorems is a grading artifact.
    ROOT / "STATE.md",
]

# Ledger and registry field names. These are schema, not declarations.
FIELDS = {
    "source_ref", "context_source_ref", "source_scope", "source_fidelity",
    "source_note", "prior_art", "proposed_by", "lean_artifact", "scope_delta",
    "novelty_checks", "content_sha256", "next_id", "schema_version",
    "root_import", "source_catalog", "atlas_declaration", "bridge_review",
    "ai_bridge_status", "original_source_refs", "paper_reference",
    "candidate_formalizations", "formal_library_search", "inspection_state",
    "relationship_review", "result_shape", "related_result_ids",
}

# Print's own notation, transliterated into ASCII by the ledger.
NOTATION = {
    "C_1", "C_j", "C_i", "C_m", "G_j", "Q_j", "Sigma_W", "Delta_M", "MM_2",
    "eps_0", "bar_1", "z_1", "d_1", "d_0d_1", "I_delta", "B_delta", "N_eps",
}

# Tooling and external names a grading note may legitimately cite.
EXTERNAL = {
    "check_print_axioms", "check_public_api", "validate_conjectures",
    "lean_build_targets", "agent_gate", "generate_declaration_index",
    "check_cited_declarations",
    "MeasureTheory.volume", "MvPolynomial.support", "MvPolynomial.totalDegree",
    "List.length", "Computability.Encoding", "Computability.finEncodingList",
    "Turing.TM2OutputsInTime", "TM2ComputableInPolyTime", "support.card",
    "Rat.cast_le", "Finset.sum_fiberwise",
}

# The trailing `'` is inside the token, not a boundary: Lean's primed names
# (`accuracySupOn_eq_sup'`) are ordinary declarations, and a `\b` anchor at the
# end silently drops the prime and then reports the unprimed name as missing.
# That false positive was this script's own first bug.
TOKEN = re.compile(r"\b[A-Za-zΔ][A-Za-z0-9_.Δ₀-₉]*_[A-Za-z0-9_.Δ₀-₉]*'*")
SUFFIXES = (".py", ".sh", ".txt", ".md", ".json", ".yaml", ".lean", ".tex", ".pdf")


def looks_like_declaration(name: str) -> bool:
    """A Lean theorem name, as opposed to print's subscripted notation.

    The discriminator is shape rather than a list: `behaviorEq_of_child_eq_zero`
    and `gap_mem_gapBox` are declaration-shaped, while `C_j`, `theta_0`, `Pa_G`
    and `d_0d_1` are a letter with a subscript, which is how the source writes
    its variables and how the ledger transliterates them.

    Two underscores, or one underscore beside a camelCase hump, is the rule.
    A single-underscore all-lowercase name such as `cpt_sum` is therefore not
    checked -- that is a deliberate gap, because print's notation lives in the
    same shape and a checker that cried wolf on `theta_0` would be turned off.
    """
    if name.endswith(SUFFIXES):
        return False
    body = name.split(".")[-1]
    if body.count("_") >= 2:
        return True
    return "_" in body and re.search(r"[a-z][A-Z]", body) is not None


def load_declarations() -> tuple[set[str], set[str]]:
    if not INDEX.exists():
        print(
            "check_cited_declarations: docs/status/declaration-index.json is "
            "missing; run scripts/generate_declaration_index.py --write first",
            file=sys.stderr,
        )
        raise SystemExit(2)
    raw = json.loads(INDEX.read_text(encoding="utf-8"))
    rows = raw.get("declarations", raw) if isinstance(raw, dict) else raw
    collected: list[object] = []
    if isinstance(rows, list):
        for row in rows:
            if isinstance(row, dict):
                collected.append(row.get("name") or row.get("declaration"))
            else:
                collected.append(row)
    elif isinstance(rows, dict):
        collected.extend(rows.keys())
    full = {name for name in collected if isinstance(name, str) and name}
    return full, {name.split(".")[-1] for name in full}


def check_ledger_pointers(full: set[str], short: set[str]) -> list[str]:
    """Ledger fields that hold declaration names must resolve.

    The prose scan above cannot see these. Its token test requires an
    underscore, deliberately, so that print's `C_j` and `theta_0` do not trip
    it — and the ledger's most load-bearing pointers are underscore-free
    CamelCase: `IsO27EdgeSurvivalRegion`, `IsBoltzmannRiskRate`, `O24Solution`,
    `O24Constructor`. Every one of them was invisible to the check that exists
    to make a cited name followable.

    Reading the fields structurally is the right fix rather than loosening the
    regex, because here the field *is* the type declaration: `lean`,
    `answer_admissible` and `answer_correct` hold names and nothing else.
    `answer_candidate` is excluded — it holds Lean *type expressions* such as
    `Set (ℝ × ℝ)`, which name no single declaration.
    """
    ledger = json.loads((ROOT / "conjectures.yaml").read_text(encoding="utf-8"))
    failures = []
    for row in ledger["conjectures"]:
        names = [row.get("lean") or ""]
        for field in ("answer_admissible", "answer_correct"):
            names.extend(row.get(field) or [])
        for name in names:
            if not name:
                continue
            if name in full or name.split(".")[-1] in short:
                continue
            failures.append(
                f"conjectures.yaml: {row['id']} points at `{name}`, which no "
                "declaration in the index carries"
            )
    return failures


def check_absences(full: set[str]) -> list[str]:
    """A `blocked` row claims declarations are missing; hold it to that.

    This is `check_cited_declarations` inverted. The forward check catches a row
    pointing at a theorem that does not exist; this one catches a row claiming a
    substrate is absent after somebody built it. Without it, a blocked row is a
    to-do comment inside a machine-checked file: it was true when written, it
    goes stale silently, and the reader has no way to tell which.

    **The stale-index dependency bites in the quiet direction here.** The
    forward check fails loudly on a stale index — it reports a real declaration
    as missing. This one does the opposite: an index that predates the
    substrate's arrival makes the tripwire *not fire*, and the row keeps
    claiming blocked. Regenerate the index after building the targets, exactly
    as the module docstring above says, or this check answers about a tree that
    no longer exists.
    """
    ledger = json.loads((ROOT / "conjectures.yaml").read_text(encoding="utf-8"))
    failures = []
    for row in ledger["conjectures"]:
        if row.get("kind") != "blocked":
            continue
        for name in row.get("absent_declarations", []):
            if name in full:
                failures.append(
                    f"conjectures.yaml: {row['id']} is blocked on `{name}`, "
                    "which now exists. The substrate arrived — re-grade the row "
                    "rather than leaving it to claim a gap that is closed"
                )
    return failures


def main() -> int:
    full, short = load_declarations()
    known = FIELDS | NOTATION | EXTERNAL
    failures: list[str] = []
    for path in SCANNED:
        if not path.exists():
            failures.append(f"scanned artifact missing: {path.relative_to(ROOT)}")
            continue
        text = path.read_text(encoding="utf-8")
        seen: set[str] = set()
        for match in TOKEN.finditer(text):
            name = match.group(0).rstrip(".")
            if name in seen or name in known:
                continue
            base = name.split(".")[-1]
            if base in known or name in full or base in short:
                continue
            # An English possessive looks exactly like a Lean prime: `foo's`
            # matches as `foo'`, because the trailing `'` is inside the token so
            # that genuinely primed names survive. If dropping it resolves, the
            # apostrophe was grammar. This cannot mask a real miss -- `foo` has
            # to exist for the name to resolve at all -- and it is the second
            # time this one regex has produced a false positive about prose that
            # was correct.
            unpossessed = name.rstrip("'")
            if unpossessed != name and (
                unpossessed in full or unpossessed.split(".")[-1] in short
            ):
                continue
            if not looks_like_declaration(name):
                continue
            seen.add(name)
            failures.append(
                f"{path.relative_to(ROOT)} names `{name}`, which no declaration "
                "in the index carries"
            )
    failures.extend(check_ledger_pointers(full, short))
    failures.extend(check_absences(full))
    if failures:
        for line in failures:
            print(f"check_cited_declarations error: {line}", file=sys.stderr)
        print(
            "check_cited_declarations error: a grading artifact points at a "
            "theorem that does not exist. Correct the name, or add it to the "
            "vocabulary lists in this script if it is notation rather than a "
            "declaration.",
            file=sys.stderr,
        )
        return 1
    blocked_rows = [
        row
        for row in json.loads(
            (ROOT / "conjectures.yaml").read_text(encoding="utf-8")
        )["conjectures"]
        if row.get("kind") == "blocked"
    ]
    absences = sum(len(row["absent_declarations"]) for row in blocked_rows)
    print(
        f"cited declarations ok: {len(SCANNED)} grading artifacts, every named "
        f"declaration resolves against {len(full)} indexed names; "
        f"{absences} claimed absences across {len(blocked_rows)} blocked rows "
        "are still absent"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
