#!/usr/bin/env python3
"""Collect every module's `## Explicit non-claims` section into one page.

The atlas's claim is not that it proves a lot; it is that what it proves is
exactly what it says. That only means something if a reader can *enumerate* the
exclusions, and until now they were scattered across module docstrings — 28 of
them, each visible only to someone already reading that file.

This reads the existing convention rather than introducing a new one: a
`## Explicit non-claims` heading inside a module's `/-! ... -/` docstring, with
everything up to the next heading of the same level. Nothing needs annotating.

`--check` verifies the generated page is current, for the gate.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEAN_ROOT = ROOT / "AISafetyAtlas"
OUT = ROOT / "docs" / "status" / "non-claims.md"

HEADING = re.compile(r"^##\s+Explicit non-claims\s*$")
ANY_H2 = re.compile(r"^##\s+\S")


def module_name(path: Path) -> str:
    rel = path.relative_to(ROOT).with_suffix("")
    return ".".join(rel.parts)


def sections() -> list[tuple[str, str]]:
    """(module, body) for every module carrying a non-claims section."""
    found: list[tuple[str, str]] = []
    for path in sorted(LEAN_ROOT.rglob("*.lean")):
        if "Examples" in path.parts:
            continue
        lines = path.read_text().split("\n")
        for i, line in enumerate(lines):
            if not HEADING.match(line):
                continue
            body: list[str] = []
            for follow in lines[i + 1 :]:
                if ANY_H2.match(follow) or follow.strip() == "-/":
                    break
                body.append(follow)
            text = "\n".join(body).strip()
            if text:
                found.append((module_name(path), text))
            break
    return found


def render(found: list[tuple[str, str]]) -> str:
    out = [
        "# Explicit non-claims",
        "",
        "*Generated by `scripts/generate_non_claims.py`. Do not edit — change the",
        "module docstring instead.*",
        "",
        "Every `## Explicit non-claims` section in the library, in one place.",
        "",
        "A formalization is only as useful as its boundary is legible. These are the",
        "statements the atlas deliberately does **not** make: hypotheses it assumes",
        "rather than derives, printed results it does not reach, and inferences a",
        "reader might expect to follow from what is here and which do not. They are",
        "part of the result, not a disclaimer attached to it.",
        "",
        f"**{len(found)} modules** carry one.",
        "",
        "---",
        "",
    ]
    for module, body in found:
        out.append(f"## `{module}`")
        out.append("")
        out.append(body)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    found = sections()
    if not found:
        print(
            "generate_non_claims: no `## Explicit non-claims` sections found — the "
            "convention must have changed, so this page would be silently empty",
            file=sys.stderr,
        )
        return 1
    page = render(found)
    if check:
        if not OUT.exists() or OUT.read_text() != page:
            print(
                f"generated file is out of date: {OUT.relative_to(ROOT)}. "
                "Re-run scripts/generate_non_claims.py",
                file=sys.stderr,
            )
            return 1
        print(f"non-claims page ok: {len(found)} modules")
        return 0
    OUT.write_text(page)
    print(f"updated {OUT.relative_to(ROOT)} ({len(found)} modules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
