#!/usr/bin/env python3
"""Generate current status and Lean declaration checks from registry data."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "registry.yaml"
CONJECTURES = ROOT / "conjectures.yaml"
TASKS = ROOT / "tasks.yaml"
SEARCH_EVIDENCE = ROOT / "docs/provenance/formalization-search.json"
STATUS = ROOT / "docs/status/formalization-status.md"
BY_AREA = ROOT / "docs/status/by-area.md"
CONTRIBUTOR_TASKS = ROOT / "docs/guide/contributor-tasks.md"
CONJECTURE_CHECKS = ROOT / "AISafetyAtlas/Conjectures/Checks.lean"
SOURCE_INDEX = ROOT / "docs/status/sources/README.md"
SURVEY_SOURCE_REPORT = ROOT / "docs/status/sources/brcic-yampolskiy-2023.md"
LANDSCAPE_INDEX = ROOT / "docs/status/landscape-index.md"
AGENT_INDEX = ROOT / "docs/agent/INDEX.md"
AGENT_BY_ID = ROOT / "docs/agent/by-id.json"
AGENT_SEARCH_SUMMARY = ROOT / "docs/agent/search-summary.json"
STATE = ROOT / "STATE.md"
LAKEFILE = ROOT / "lakefile.toml"
CITATION = ROOT / "CITATION.cff"
RELEASES_DIR = ROOT / "docs/releases"
README = ROOT / "README.md"
LEAN_CHECKS = ROOT / "AISafetyAtlas/Examples/Registry.lean"
README_START = "<!-- BEGIN GENERATED REGISTRY SCOPE -->"
README_END = "<!-- END GENERATED REGISTRY SCOPE -->"
STATE_START = "<!-- BEGIN GENERATED REGISTRY SNAPSHOT -->"
STATE_END = "<!-- END GENERATED REGISTRY SNAPSHOT -->"
ROUTING_START = "<!-- BEGIN GENERATED ROUTING -->"
ROUTING_END = "<!-- END GENERATED ROUTING -->"
RELEASE_START = "<!-- BEGIN GENERATED RELEASE STATUS -->"
RELEASE_END = "<!-- END GENERATED RELEASE STATUS -->"
COVERAGE_RELATIONSHIPS = {"EXACT", "EQUIVALENT"}
SEARCH_SUMMARY_MAX_PATHS = 3



def all_declarations(registry: dict) -> list[str]:
    """Every atlas declaration in the ledger, claims and artifacts alike."""
    return unique([
        d["atlas_declaration"]
        for r in registry["results"] if r["lean_artifact"] is not None
        for d in r["lean_artifact"]["declarations"]
    ])


def claim_rows(registry: dict) -> list[dict]:
    """Rows stating something a source asserted."""
    return [r for r in registry["results"] if "informal_claim" in r]


def survey_claim_rows(registry: dict) -> list[dict]:
    """The closed Brčić–Yampolskiy claim block, not every claim in the ledger."""
    return [r for r in claim_rows(registry) if r["id"].startswith("BY-")]


def artifact_rows(registry: dict) -> list[dict]:
    """Rows recording a formalization that stands on its own account."""
    return [r for r in registry["results"] if "informal_claim" not in r]


def open_conjectures(conjectures: dict) -> int:
    return sum(c["status"] == "OPEN" for c in conjectures["conjectures"])


def code_list(items: list[str]) -> str:
    return "<br>".join(f"`{item}`" for item in items)


def record_declarations(record: dict) -> list[str]:
    """Return one normalized list for singular and plural ledger spellings."""
    if record.get("declarations") is not None:
        return list(record["declarations"])
    declaration = record.get("declaration")
    return [declaration] if declaration else []


def unique(items: list[str]) -> list[str]:
    return list(dict.fromkeys(items))


def has_reproduced_relationship(result: dict, relationships: set[str]) -> bool:
    return any(
        record.get("reproduced") and record.get("relationship") in relationships
        for record in result["formalizations"]
    )


def strongest_relationship(result: dict) -> str:
    reproduced = [
        record.get("relationship")
        for record in result["formalizations"]
        if record.get("reproduced") and record.get("relationship")
    ]
    coverage = [r for r in reproduced if r in COVERAGE_RELATIONSHIPS]
    if coverage:
        return code_list(unique(coverage))
    if reproduced:
        return code_list(unique(reproduced))
    return "—"


def render_survey_source_report(registry: dict) -> str:
    """Per-source coverage report for the Brčić–Yampolskiy survey.

    One report among several: a source records provenance, and no source defines
    what the workbench owes. Rows here are inputs the atlas has catalogued, not a
    backlog it is measured against.
    """
    results = survey_claim_rows(registry)
    lines = [
        "<!-- Generated by scripts/generate_registry_views.py; do not edit directly. -->",
        "# Source report — Brčić–Yampolskiy impossibility survey",
        "",
        "Coverage report for one catalogued source",
        "([CSUR](https://doi.org/10.1145/3603371)), generated from",
        "[`registry.yaml`](../../../registry.yaml). A source contributes results; it",
        "does not set the workbench's agenda, and an uncovered row is a catalogued",
        "input rather than an outstanding obligation. `Formalization` is the",
        "strongest reproduced relationship; `Bridge` is the AI-system interpretation",
        "review state; `Candidate` counts manually discovered leads not yet accepted",
        "as coverage. Workbench totals live in",
        "[formalization status](../formalization-status.md); next actions in",
        "[open work](../../guide/open-work.md).",
        "",
        "| ID | Survey result | Informal claim | Source paper(s) | Formalization "
        "| Atlas declarations | Bridge | Candidate leads |",
        "|---|---|---|---|---|---|---|---:|",
    ]
    catalog = registry["source_catalog"]
    for result in results:
        claim = result["informal_claim"].replace("|", "\\|")
        leads = result.get("candidate_formalizations", [])
        candidate = str(len(leads)) if leads else "—"
        refs = result.get("original_source_refs") or []
        papers = (
            "<br>".join(_md_cell(_short_citation(catalog[ref]["citation"])) for ref in refs)
            if refs
            else "—"
        )
        artifact = result["lean_artifact"]
        declarations = (
            code_list(
                sorted({d["atlas_declaration"] for d in artifact["declarations"]})
            )
            if artifact is not None
            else "—"
        )
        lines.append(
            f"| {result['id']} | {result['name']} | {claim} | {papers} | "
            f"{strongest_relationship(result)} | {declarations} | "
            f"`{result['ai_bridge_status']}` | {candidate} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_status(registry: dict, search_evidence: dict) -> str:
    results = claim_rows(registry)
    survey_results = survey_claim_rows(registry)
    all_results = registry["results"]
    covered = [
        result
        for result in results
        if has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS)
    ]
    related_only = [
        result
        for result in results
        if not has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS)
        and has_reproduced_relationship(result, {"RELATED"})
    ]
    formalizations = [
        record for result in all_results for record in result["formalizations"]
    ]
    artifacts = [
        declaration
        for result in all_results
        if result["lean_artifact"] is not None
        for declaration in result["lean_artifact"]["declarations"]
    ]
    declared_reproduced = sum(bool(record.get("reproduced")) for record in formalizations)
    # Records may exceed unique names when one declaration legitimately serves
    # two rows. Left unexplained, the gap reads as an off-by-one; the validator
    # forbids two *owners*, so any gap here is deliberate and can be named.
    names = [artifact["atlas_declaration"] for artifact in artifacts]
    shared = sorted({name for name in names if names.count(name) > 1})
    duplicate_note = (
        f" (one declaration on two rows: {', '.join(f'`{n}`' for n in shared)})"
        if shared
        else ""
    )
    bridges = [artifact for artifact in artifacts if artifact["type"] == "BRIDGE"]
    wrappers = [artifact for artifact in artifacts if artifact["type"] == "WRAPPER"]
    new_proofs = [artifact for artifact in artifacts if artifact["type"] == "NEW_PROOF"]
    references = [artifact for artifact in artifacts if artifact["type"] == "REFERENCE"]
    rows_with_bridge = sum(
        result["lean_artifact"] is not None
        and any(d["type"] == "BRIDGE" for d in result["lean_artifact"]["declarations"])
        for result in all_results
    )
    rows_wrapper_only = sum(
        result["lean_artifact"] is not None
        and all(d["type"] == "WRAPPER" for d in result["lean_artifact"]["declarations"])
        for result in all_results
    )
    candidate_leads = sum(
        len(result.get("candidate_formalizations") or []) for result in results
    )
    external = [
        (result, record)
        for result in all_results
        for record in result["formalizations"]
        if record["framework"] != "Lean" and record["reproduced"]
    ]
    reviewed_results = sum(
        result.get("ai_bridge_status", "HUMAN_REVIEW") != "HUMAN_REVIEW" for result in results
    )
    candidate_results = sum(
        any(hit["hit_count"] for hit in evidence["candidate_hits"].values())
        for evidence in search_evidence["results"].values()
    )

    lines = [
        "<!-- Generated by scripts/generate_registry_views.py; do not edit directly. -->",
        "# Formalization Status",
        "",
        "Sources: [`registry.yaml`](../../registry.yaml) and",
        "[`formalization-search.json`](../provenance/formalization-search.json).",
        "Regenerate: `python3 scripts/generate_registry_views.py`.",
        "",
        "Workbench capital vs statement-match grades: see",
        "[methodology](../guide/methodology.md#workbench-metrics-vs-statement-match-grades).",
        "`RELATED` is scoped capital (not failed match; not by itself finished).",
        "Statement-match is not the primary success score.",
        "",
        "| Metric | Current |",
        "|---|---:|",
        f"| Results stating a source claim | {len(results)} |",
        f"| Results recording a formalization only | {len(artifact_rows(registry))} |",
        f"| Registry results with atlas Lean (any grade) | {sum(result['lean_artifact'] is not None for result in all_results)} |",
        f"| Claim results with statement-match (`EXACT` or `EQUIVALENT`) | {len(covered)} |",
        f"| Claim results with workbench formalizations (`RELATED` only) | {len(related_only)} |",
        # "Verified" overstated it: the ledger *declares* reproduction, and the
        # gate does not re-execute those builds. Say what the number counts.
        f"| Formalization records | {len(formalizations)} |",
        f"| … declaring reproduction (self-attested; see methodology) "
        f"| {declared_reproduced} |",
        f"| Atlas Lean theorem declarations (unique names) | {len(all_declarations(registry))} |",
        f"| Registry Lean declaration records | {len(artifacts)}"
        f"{duplicate_note} |",
        f"| … of which `WRAPPER` | {len(wrappers)} |",
        f"| … of which `BRIDGE` | {len(bridges)} |",
        f"| … of which `NEW_PROOF` | {len(new_proofs)} |",
        f"| … of which `REFERENCE` | {len(references)} |",
        f"| Registry rows whose atlas Lean is wrapper-only | {rows_wrapper_only} |",
        f"| Registry rows with at least one `BRIDGE` declaration | {rows_with_bridge} |",
        f"| Structured `candidate_formalizations` leads | {candidate_leads} |",
        f"| Reproduced external formalization records | {len(external)} across {len({result['id'] for result, _ in external})} registry results |",
        f"| Claim results with reviewed AI-system bridges | {reviewed_results} |",
        f"| Brčić–Yampolskiy survey rows catalogued (that source, complete) | {len(survey_results)} / {registry['survey']['expected_result_count']} |",
        f"| Survey rows with atlas Lean (any grade) | {sum(result['lean_artifact'] is not None for result in survey_results)} |",
        f"| … with six-corpus discovery evidence (that source, complete) | {len(search_evidence['results'])} / {len(survey_results)} |",
        "",
        "## Registry Lean declarations",
        "",
        "| ID | Registry result | Formalization relationships | Source declarations | Atlas declarations and layers |",
        "|---|---|---|---|---|",
    ]

    for result in all_results:
        artifact = result["lean_artifact"]
        if artifact is None:
            continue
        declarations = artifact["declarations"]
        sources = unique(
            [
                source
                for declaration in declarations
                for source in declaration["source_declarations"]
            ]
        )
        atlas = [
            f"{declaration['atlas_declaration']} ({declaration['type']})"
            for declaration in declarations
        ]
        relationships = unique(
            [record.get("relationship") for record in result["formalizations"] if record.get("relationship")]
        )
        lines.append(
            f"| {result['id']} | {result['name']} | {code_list(relationships)} | "
            f"{code_list(sources) or '—'} | {code_list(atlas)} |"
        )

    lines.extend(
        [
            "",
            "The generated declaration-presence checks live in",
            "[`AISafetyAtlas/Examples/Registry.lean`](../../AISafetyAtlas/Examples/Registry.lean).",
            "The hand-written `PublicAPI` examples separately protect the intended theorem",
            "signatures and root-import usability.",
            "",
            "## Reproduced external formalization records",
            "",
            "| ID | Registry result | Framework | Declaration | Relationship | Reproduction command |",
            "|---|---|---|---|---|---|",
        ]
    )
    for result, record in external:
        lines.append(
            f"| {result['id']} | {result['name']} | {record['framework']} | "
            f"{code_list(record_declarations(record)) or '—'} | "
            f"{record.get('relationship', '—')} | "
            f"`{record['build_command']}` |"
        )

    lines.extend(
        [
            "",
            "Additional reproduced variants and adjacent developments, including vNM",
            "expected utility, remain provenance rather than extra survey coverage; see",
            "[`external-formalizations.md`](../provenance/external-formalizations.md) and the",
            "[landscape index](landscape-index.md).",
            "",
            "## Discovery coverage",
            "",
            f"All {len(survey_results)} rows have a **baseline classical six-corpus** search",
            "(Mathlib, Isabelle AFP, Rocq Undecidability, HOL4, HOL Light, Agda stdlib);",
            f"{candidate_results} rows produced raw candidate-file hits. That pass is",
            "**scoped** negative/positive evidence for those corpora only — it does not",
            "search third-party Lean packages (Foundation, KolmogorovMathlib, SocialChoiceLean,",
            "DASH, …). Manually discovered package leads are recorded as",
            "`candidate_formalizations` on a claim row, or as an artifact row when the",
            "formalization stands on its own account. Candidate hits are discovery",
            "evidence, not verified formalizations. Relationship labels are",
            "`EXACT`, `EQUIVALENT`, `RELATED`, `DEPENDENCY_ONLY`, and `UNCLEAR`.",
            "An AI-safety interpretation remains `HUMAN_REVIEW` unless it has been",
            "separately defined and reviewed.",
            "",
        ]
    )
    return "\n".join(lines)


def _md_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _inline_code(text: object) -> str:
    """Render a code span safely when the value itself contains backticks."""
    return f"`{_md_cell(str(text)).replace('`', '&#96;')}`"


def _short_citation(citation: str, limit: int = 120) -> str:
    citation = " ".join(citation.split())
    if len(citation) <= limit:
        return citation
    return citation[: limit - 1] + "…"


def render_conjecture_checks(conjectures: dict) -> str:
    """Require every conjecture statement named in the ledger to be a closed Prop.

    The ledger records a Lean name as a string, and a string that looks like a
    declaration is not one. Emitting `example : Prop := <name>` under CI is what
    makes the claim "this conjecture has a compiling statement" true rather than
    asserted, and it rejects a declaration that is not a proposition — `#check`
    would only print whatever type the declaration happens to have. Mirrors
    `AISafetyAtlas/Examples/Registry.lean`, which does the weaker `#check` job
    for registry declarations whose types are not constrained.
    """
    entries = conjectures["conjectures"]
    modules = sorted({entry["lean"].rsplit(".", 1)[0] for entry in entries})
    lines = [
        "-- Generated by scripts/generate_registry_views.py; do not edit directly.",
        "module",
        "",
        *(f"public import {module}" for module in modules),
        "",
        "/-!",
        "# Conjecture statement checks",
        "",
        "Every Lean name recorded in `conjectures.yaml`, required to be a closed",
        "proposition. `example : Prop := name` fails unless the declaration is",
        "`Prop`-valued; defining a proposition asserts nothing about its truth.",
        "Nothing here is proved, and this module is not on the atlas root import.",
        "-/",
        "",
    ]
    for entry in entries:
        lines.append(f"-- {entry['id']} ({entry['status']})")
        # `example : Prop := name` requires the declaration to *be* a closed
        # proposition. `#check` would only print whatever type it happens to
        # have, which lets a non-Prop declaration through.
        lines.append(f"example : Prop := {entry['lean']}")
    lines.append("")
    return "\n".join(lines)



def render_contributor_tasks(tasks: dict) -> str:
    """Contributor task board, rendered from `tasks.yaml`.

    The board used to be maintained directly in Markdown while GitHub issues
    carried the same units, so a task's state lived in two places and drifted.
    One maintained record, many generated conveniences: the prose bodies stay
    prose — whether a task is worth doing is not a thing a script decides — but
    id, size, rung and done/open state become checkable, and the document cannot
    disagree with them.

    Issues are referenced, never mirrored. Their lifecycle stays on GitHub.
    """
    lines = [
        "<!-- Generated by scripts/generate_registry_views.py from tasks.yaml;"
        " do not edit directly. -->",
        tasks["preamble"],
        "",
    ]
    for task in tasks["tasks"]:
        hashes = "#" * task["heading_level"]
        lines.append(
            f"{hashes} {task['id']} — {task['title']} "
            f"({task['size']}) — **{task['rung']}**"
        )
        lines.append("")
        lines.append(task["body"])
        lines.append("")
    lines.append(tasks["footer"])
    return "\n".join(lines).rstrip("\n") + "\n"



def render_routing() -> str:
    """One routing table, rendered wherever a contributor might start.

    It existed four times — README prose, the agent index, the setup script's
    output, and the task-board preamble — each phrased differently. A newcomer
    does not have too much to learn here; they had too many places telling them
    where to begin, and the divergence between those places was itself the drift.

    Deliberately says nothing about *why* anything is arranged this way. Purpose
    and argument live in prose that carries no facts and therefore cannot go
    stale; this table carries only facts and therefore must be generated.
    """
    rows = [
        (
            "a pointer to a result, or a proof, that is not recorded here",
            "the [discovery issue form]"
            "(https://github.com/mbrcic/ai-safety-formalization-atlas/issues/new"
            "?template=known-formalization.yml) — we classify it and place it",
            "nothing to install",
        ),
        (
            "a correction to a record you have already found",
            "the ledger file that holds it",
            "`scripts/setup.sh --pointer`",
        ),
        (
            "an open question and no proof",
            "`conjectures.yaml` + a module under `AISafetyAtlas/Conjectures/`",
            "add it to `scripts/lean_build_targets.txt`, then build + gate",
        ),
        (
            "a proof to write, or any Lean change",
            "the facade for your area (see Domain imports)",
            "`scripts/setup.sh`, then build + gate + `check_print_axioms.py`",
        ),
        (
            "a change to a contributor task",
            "`tasks.yaml` — never the generated Markdown",
            "regenerate + gate",
        ),
        (
            "evidence that something does not exist",
            "`novelty_checks` in `docs/provenance/formalization-search.json`",
            "regenerate + gate",
        ),
        (
            "a new source to catalogue",
            "`source_catalog` in `registry.yaml`, with its `role`",
            "regenerate + gate",
        ),
    ]
    lines = [
        ROUTING_START,
        "<!-- Generated by scripts/generate_registry_views.py; do not edit by hand. -->",
        "",
        "| I have… | It goes in | Then |",
        "|---|---|---|",
        *(f"| {have} | {where} | {then} |" for have, where, then in rows),
        "",
        "**regenerate** `python3 scripts/generate_registry_views.py` ·"
        " **gate** `./scripts/agent_gate.sh` · **build** `lake build`",
        "",
        "Nothing here needs the whole picture: take the row that matches what you",
        "have and ignore the rest.",
        ROUTING_END,
    ]
    return "\n".join(lines)


def render_by_area(registry: dict) -> str:
    """The atlas indexed by mathematical area, spanning the single registry ledger.

    A contributor arrives knowing an area, not an identifier. This is the entry
    point for "I work on provability logic / learning theory / social choice —
    what is here, and what is not." An area with no shipped Lean is not a
    backlog; it is where the workbench is thin, which is useful to know.
    """
    tags = registry["vocabulary"]["tag"]
    shipped: dict[str, list[str]] = {tag: [] for tag in tags}
    mapped: dict[str, list[str]] = {tag: [] for tag in tags}

    for result in registry["results"]:
        artifact = result["lean_artifact"]
        declarations = (
            sorted(
                {
                    declaration["atlas_declaration"]
                    for declaration in artifact["declarations"]
                }
            )
            if artifact is not None
            else []
        )
        for tag in result["tags"]:
            if declarations:
                shipped[tag].append(
                    f"| {result['id']} | {result['name']} | "
                    f"{code_list(declarations)} |"
                )
            else:
                mapped[tag].append(f"| {result['id']} | {result['name']} |")

    lines = [
        "<!-- Generated by scripts/generate_registry_views.py; do not edit directly. -->",
        "# The atlas by mathematical area",
        "",
        "Generated from [`registry.yaml`](../../registry.yaml). Areas come from the shared `tag`",
        "vocabulary; a result carries every area it belongs to, so entries repeat",
        "across sections.",
        "",
        "**Shipped** means an atlas Lean declaration exists — importable, kernel-checked,",
        "under the axiom policy. **Catalogued** means the result is recorded with its",
        "provenance and no Lean stands behind it yet. A thin area is not a backlog; it",
        "is where the workbench is thin, which is the useful thing to know before",
        "picking work. Grades and reproduction evidence:",
        "[formalization status](formalization-status.md).",
        "",
        "| Area | Shipped | Catalogued |",
        "|---|---:|---:|",
    ]
    for tag in tags:
        anchor = tag.replace("-", "-")
        lines.append(
            f"| [{tag}](#{anchor}) | {len(shipped[tag])} | {len(mapped[tag])} |"
        )
    lines.append("")

    for tag in tags:
        lines += [f"## {tag}", ""]
        if shipped[tag]:
            lines += [
                "| ID | Result | Atlas declarations |",
                "|---|---|---|",
                *shipped[tag],
                "",
            ]
        else:
            lines += ["No atlas Lean in this area yet.", ""]
        if mapped[tag]:
            lines += [
                "Catalogued, no atlas Lean:",
                "",
                "| ID | Result |",
                "|---|---|",
                *mapped[tag],
                "",
            ]
    return "\n".join(lines)


def render_source_index(registry: dict) -> str:
    """Catalogued sources, split by the only distinction that carries rules.

    A *directory* is a curated map whose purpose is to hand work to others: it
    enumerates pointers and has no statement of its own, so it is never graded
    against and its entry count never becomes a metric. A *work* is
    statement-bearing — a paper, report, or library that makes a claim of its own
    — and is the only thing a statement-match grade can compare to. Listing a directory signals that we read it and makes the atlas
    reachable from that direction; it creates no obligation to cover it.
    """
    sources = registry["source_catalog"]
    directories = {
        key: value
        for key, value in sources.items()
        if value.get("role") == "directory"
    }
    works = len(sources) - len(directories)
    lines = [
        "<!-- Generated by scripts/generate_registry_views.py; do not edit directly. -->",
        "# Sources",
        "",
        "Catalogued in [`registry.yaml`](../../../registry.yaml): "
        f"**{len(directories)}** directories and **{works}** works.",
        "",
        "A **directory** is a curated map whose purpose is to hand work to others.",
        "It enumerates pointers and states nothing of its own, so it is never the",
        "thing a grade compares against, and its entry count never becomes a metric.",
        "Listing one means we read it and can be found from that direction — not that",
        "we owe it coverage. A **work** is statement-bearing: it makes a claim of its",
        "own that a statement-match grade can be related to.",
        "",
        "## Directories",
        "",
        "| Source | Retrieved | Locator |",
        "|---|---|---|",
    ]
    for key, value in sorted(directories.items()):
        locator = value.get("locator")
        link = f"[{locator}]({locator})" if locator else "—"
        lines.append(f"| `{key}` | {value.get('retrieved') or '—'} | {link} |")
    report_paths = sorted(
        path
        for path in SOURCE_INDEX.parent.glob("*.md")
        if path.name != SOURCE_INDEX.name
    )
    lines += [
        "",
        "## Per-source coverage reports",
        "",
        *(
            f"- [`{path.name}`]({path.name})"
            for path in report_paths
        ),
        "" if report_paths else "No per-source report has been generated yet.",
        "",
        "A source without a report is one nothing has been drawn from yet. That is a",
        "normal state, not a gap.",
        "",
    ]
    return "\n".join(lines)


def render_landscape_index(registry: dict) -> str:
    lines = [
        "<!-- Generated by scripts/generate_registry_views.py; do not edit directly. -->",
        "# Landscape Index",
        "",
        "First-class atlas formalizations and public Lean surface recorded in",
        "[`registry.yaml`](../../registry.yaml) — results the workbench develops,",
        "reproduces, or exposes on its own account. Statement-match grades are",
        "reported per catalogued source and are not affected by entries here.",
        "Narrative provenance remains in [`external-formalizations.md`](../provenance/external-formalizations.md).",
        "",
        "| ID | Name | Framework | Atlas / source declarations | Root import | Reproduction |",
        "|---|---|---|---|---|---|",
    ]
    for entry in artifact_rows(registry):
        atlas_declarations = code_list(
            sorted(
                {
                    declaration["atlas_declaration"]
                    for declaration in (entry.get("lean_artifact") or {}).get("declarations", [])
                }
            )
        )
        for record in entry["formalizations"]:
            declarations = atlas_declarations or code_list(record_declarations(record)) or "—"
            root = "yes" if entry.get("root_import") else "no"
            repro = record.get("build_command") or "—"
            if repro != "—":
                repro = _inline_code(repro)
            lines.append(
                f"| {entry['id']} | {entry['name']} | {record['framework']} | "
                f"{declarations} | {root} | {repro} |"
            )
    lines.append("")
    return "\n".join(lines)


def render_state_snapshot(registry: dict, conjectures: dict) -> str:
    """Generated block embedded in STATE.md so hand counts cannot drift (R7-1).

    Every line says which population it counts. An earlier version computed
    declaration types and Lean-bearing rows over claim rows alone while calling
    them "registry", so STATE reported 13 rows and 12 wrappers against the
    status page's 22 and 14 — two generated files, one ledger, one run, and no
    way for a reader to tell which was wrong.
    """
    results = claim_rows(registry)
    covered = sum(
        has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS) for result in results
    )
    related_only = sum(
        not has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS)
        and has_reproduced_relationship(result, {"RELATED"})
        for result in results
    )
    artifacts = [
        declaration
        for result in results
        if result["lean_artifact"] is not None
        for declaration in result["lean_artifact"]["declarations"]
    ]
    lean_rows = sum(result["lean_artifact"] is not None for result in results)
    bridges = sum(a["type"] == "BRIDGE" for a in artifacts)
    wrappers = sum(a["type"] == "WRAPPER" for a in artifacts)
    reviewed = sum(result.get("ai_bridge_status", "HUMAN_REVIEW") != "HUMAN_REVIEW" for result in results)
    candidates = sum(
        len(result.get("candidate_formalizations") or []) for result in results
    )
    landscape_entries = artifact_rows(registry)
    landscape_root = sum(bool(e.get("root_import")) for e in landscape_entries)
    all_lean_rows = sum(
        result["lean_artifact"] is not None for result in registry["results"]
    )
    lines = [
        STATE_START,
        "<!-- Generated by scripts/generate_registry_views.py; do not edit by hand. -->",
        f"- Atlas Lean declarations: **{len(all_declarations(registry))}**"
        f" (claim-row WRAPPER **{wrappers}** / BRIDGE **{bridges}**).",
        f"- Results stating a source claim: **{len(results)}**;"
        f" recording a formalization only: **{len(landscape_entries)}**"
        f" (**{landscape_root}** on the public root import).",
        f"- Reviewed AI-system bridges: **{reviewed}**.",
        f"- Open conjectures: **{open_conjectures(conjectures)}**"
        f" of **{len(conjectures['conjectures'])}** recorded.",
        f"- Catalogued results with statement-match (`EXACT`/`EQUIVALENT`):"
        f" **{covered}**; with `RELATED`-only formalization: **{related_only}**."
        " Counts are results, not records.",
        f"- Rows carrying atlas Lean: **{all_lean_rows}**"
        f" (**{lean_rows}** of them claim rows);"
        f" catalogued candidate leads: **{candidates}**.",
        STATE_END,
    ]
    return "\n".join(lines)


def _read_version(path: Path, pattern: str) -> str:
    match = re.search(pattern, path.read_text(encoding="utf-8"))
    if not match:
        raise ValueError(f"could not read version from {path.relative_to(ROOT)}")
    return match.group(1)


def package_version() -> str:
    """Package version from lakefile.toml, cross-checked against CITATION.cff."""
    lake = _read_version(LAKEFILE, r'(?m)^\s*version\s*=\s*"([^"]+)"')
    citation = _read_version(CITATION, r'(?m)^\s*version\s*:\s*"?([^"\s]+)"?')
    if lake != citation:
        raise ValueError(
            f"version mismatch: lakefile.toml {lake!r} != CITATION.cff {citation!r}"
        )
    return lake


def latest_release_doc() -> str | None:
    """Highest vX.Y release note under docs/releases (committed source of truth)."""
    versions = [
        m.group(1)
        for path in RELEASES_DIR.glob("v*.md")
        if (m := re.fullmatch(r"v(\d+(?:\.\d+)*)", path.stem))
    ]
    if not versions:
        return None
    return max(versions, key=lambda v: tuple(int(p) for p in v.split(".")))


def render_release_status() -> str:
    """Release/version block for STATE.md, derived only from committed sources.

    Deliberately does not embed a git tag: the agent-gate checkout does not fetch
    tags, and a release commit predates its own tag, so a tag value cannot round-trip
    through the pre-merge --check. The canonical published set is named, not copied.
    """
    version = package_version()
    latest = latest_release_doc()
    release_line = (
        f"[`docs/releases/v{latest}.md`](docs/releases/v{latest}.md)"
        if latest is not None
        else "none recorded"
    )
    lines = [
        RELEASE_START,
        "<!-- Generated by scripts/generate_registry_views.py; do not edit by hand. -->",
        f"- Package version: **`{version}`** "
        "(`lakefile.toml`, cross-checked against `CITATION.cff`).",
        f"- Latest recorded release note: {release_line}.",
        "- Published releases are the repository's git tags / GitHub Releases —"
        " that list, not this file, is the canonical published set.",
        RELEASE_END,
    ]
    return "\n".join(lines)


def _splice(text: str, start_marker: str, end_marker: str, generated: str) -> str:
    start = text.find(start_marker)
    end = text.find(end_marker)
    if start < 0 or end < start:
        raise ValueError(
            "STATE.md generated markers are missing or out of order; "
            f"expected {start_marker!r} … {end_marker!r}"
        )
    end += len(end_marker)
    return text[:start] + generated + text[end:]


def render_state(state: str, registry: dict, conjectures: dict) -> str:
    state = _splice(
        state,
        STATE_START,
        STATE_END,
        render_state_snapshot(registry, conjectures),
    )
    state = _splice(state, RELEASE_START, RELEASE_END, render_release_status())
    return state


def render_readme(readme: str, registry: dict, conjectures: dict) -> str:
    results = claim_rows(registry)
    covered = sum(
        has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS)
        for result in results
    )
    related_only = sum(
        not has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS)
        and has_reproduced_relationship(result, {"RELATED"})
        for result in results
    )
    artifacts = [
        declaration
        for result in results
        if result["lean_artifact"] is not None
        for declaration in result["lean_artifact"]["declarations"]
    ]
    reviewed = sum(
        result.get("ai_bridge_status", "HUMAN_REVIEW") != "HUMAN_REVIEW" for result in results
    )
    landscape_entries = artifact_rows(registry)
    landscape_root = sum(bool(e.get("root_import")) for e in landscape_entries)
    # Absolute workbench capital. No denominators: a denominator reads as a
    # completion target, and no single source defines what this workbench owes.
    generated = "\n".join(
        [
            README_START,
            "| Metric | Current |",
            "|---|---:|",
            f"| Atlas Lean declarations | **{len(all_declarations(registry))}** |",
            f"| Results stating a source claim | **{len(results)}** |",
            f"| Results recording a formalization only | "
            f"**{len(landscape_entries)}** ({landscape_root} on root import) |",
            f"| Reviewed AI-system bridges | **{reviewed}** |",
            f"| Open conjectures | **{open_conjectures(conjectures)}** |",
            f"| Catalogued results with statement-match | **{covered}** |",
            f"| Catalogued results with `RELATED`-only formalization | **{related_only}** |",
            "",
            "`EXACT`/`EQUIVALENT` = conservative citation grade (completely",
            "formalization-covered source statements). `RELATED` = value-based scoped",
            "formalization, with documented deltas; it does **not by itself** mean",
            "unfinished, but postponed until justified (paper residuals stay in",
            "provenance). Counts above are **catalogued results**, not",
            "formalization records: one result may carry several. Detail:",
            "[formalization status](docs/status/formalization-status.md);",
            "[by mathematical area](docs/status/by-area.md);",
            "per-source reports under [`docs/status/sources/`](docs/status/sources/).",
            README_END,
        ]
    )
    start = readme.find(README_START)
    end = readme.find(README_END)
    if start < 0 or end < start:
        raise ValueError("README generated-scope markers are missing or out of order")
    end += len(README_END)
    readme = readme[:start] + generated + readme[end:]
    # Same file, same pass: two update() calls on one path would each start from
    # a different snapshot and the later write would revert the earlier splice.
    return _splice(readme, ROUTING_START, ROUTING_END, render_routing())


def render_lean(registry: dict) -> str:
    artifact_declarations = [
        declaration["atlas_declaration"]
        for result in registry["results"]
        if result["lean_artifact"] is not None
        for declaration in result["lean_artifact"]["declarations"]
    ]
    declarations = unique(artifact_declarations)
    lines = [
        "module",
        "",
        "import AISafetyAtlas",
        "",
        "/-! Generated by `scripts/generate_registry_views.py`; do not edit directly. -/",
        "",
    ]
    lines.extend(f"#check {declaration}" for declaration in declarations)
    lines.append("")
    return "\n".join(lines)


def compact_formalization(record: dict) -> dict:
    """Agent-facing formalization fields only (omit build logs / license prose)."""
    return {
        "framework": record.get("framework"),
        "relationship": record.get("relationship"),
        "reproduced": record.get("reproduced"),
        "declaration": record.get("declaration"),
        "declarations": record_declarations(record),
        "module": record.get("module"),
        "repository": record.get("repository"),
        "version": record.get("version"),
    }


def compact_result(result: dict) -> dict:
    """Compact survey row for agent lookup without loading full registry.yaml."""
    lean = result.get("lean_artifact")
    lean_out = None
    if lean is not None:
        lean_out = {
            "declarations": [
                {
                    "atlas_declaration": declaration["atlas_declaration"],
                    "type": declaration["type"],
                }
                for declaration in lean.get("declarations") or []
            ]
        }
    return {
        "id": result["id"],
        "name": result["name"],
        "ai_bridge_status": result.get("ai_bridge_status"),
        "informal_claim": result.get("informal_claim"),
        "formalizations": [
            compact_formalization(record)
            for record in result.get("formalizations") or []
        ],
        "lean_artifact": lean_out,
        "candidate_count": len(result.get("candidate_formalizations") or []),
    }


def render_agent_by_id(registry: dict) -> str:
    """Compact BY-### / CLM-* / LAND-* index for agents (token-cheap vs full registry)."""
    payload = {
        "schema_version": 1,
        "generated_by": "scripts/generate_registry_views.py",
        "note": (
            "Compact agent lookup over the single results ledger. Prefer this over "
            "registry.yaml; open the full YAML only for one id when notes or "
            "candidate-formalization detail is required. A row with an informal "
            "claim states something a source asserted; a row without one records a "
            "formalization standing on its own account."
        ),
        "claim_count": len(claim_rows(registry)),
        "artifact_count": len(artifact_rows(registry)),
        "results_by_id": {
            result["id"]: compact_result(result) for result in registry["results"]
        },
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def compact_search_result(record: dict) -> dict:
    """Keep queries and non-zero corpus hits only (drop empty zero matrices)."""
    hits: dict[str, dict] = {}
    for corpus, hit in (record.get("candidate_hits") or {}).items():
        count = int(hit.get("hit_count") or 0)
        if count <= 0:
            continue
        paths = list(hit.get("paths") or [])[:SEARCH_SUMMARY_MAX_PATHS]
        hits[corpus] = {
            "hit_count": count,
            "matched_queries": list(hit.get("matched_queries") or []),
            "paths": paths,
        }
    return {
        "queries": list(record.get("queries") or []),
        "hits": hits,
        "total_hit_count": sum(item["hit_count"] for item in hits.values()),
    }


def render_agent_search_summary(search_evidence: dict) -> str:
    """Token-cheap discovery summary; prefer over formalization-search.json."""
    results = search_evidence.get("results") or {}
    compact_results = {
        result_id: compact_search_result(record)
        for result_id, record in results.items()
    }
    with_hits = sum(
        1 for record in compact_results.values() if record["total_hit_count"] > 0
    )
    payload = {
        "schema_version": 1,
        "generated_by": "scripts/generate_registry_views.py",
        "note": (
            "Compact discovery summary. Prefer this over "
            "docs/provenance/formalization-search.json. Full path lists and "
            "per-query zero counts live only in the full evidence file."
        ),
        "searched_on": search_evidence.get("searched_on"),
        "corpora": list((search_evidence.get("corpora") or {}).keys()),
        "result_count": len(compact_results),
        "results_with_hits": with_hits,
        "results": compact_results,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def update(path: Path, expected: str, check: bool) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if actual == expected:
        return False
    if check:
        print(
            f"generated file is out of date: {path.relative_to(ROOT)}",
            file=sys.stderr,
        )
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"updated {path.relative_to(ROOT)}")
    return False


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when generated files are stale",
    )
    args = parser.parse_args()

    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    conjectures = json.loads(CONJECTURES.read_text(encoding="utf-8"))
    tasks = json.loads(TASKS.read_text(encoding="utf-8"))
    search_evidence = json.loads(SEARCH_EVIDENCE.read_text(encoding="utf-8"))
    readme = README.read_text(encoding="utf-8")
    state = STATE.read_text(encoding="utf-8")

    stale = False
    stale |= update(STATUS, render_status(registry, search_evidence), args.check)
    stale |= update(BY_AREA, render_by_area(registry), args.check)
    stale |= update(
        AGENT_INDEX,
        _splice(
            AGENT_INDEX.read_text(encoding="utf-8"),
            ROUTING_START,
            ROUTING_END,
            render_routing(),
        ),
        args.check,
    )
    stale |= update(CONTRIBUTOR_TASKS, render_contributor_tasks(tasks), args.check)
    stale |= update(
        CONJECTURE_CHECKS, render_conjecture_checks(conjectures), args.check
    )
    stale |= update(
        SURVEY_SOURCE_REPORT, render_survey_source_report(registry), args.check
    )
    # The source index discovers report files from this directory. Generate
    # reports first so a newly added report is listed in the same run rather
    # than appearing only after a second regeneration.
    stale |= update(SOURCE_INDEX, render_source_index(registry), args.check)
    stale |= update(LANDSCAPE_INDEX, render_landscape_index(registry), args.check)
    stale |= update(
        AGENT_BY_ID, render_agent_by_id(registry), args.check
    )
    stale |= update(
        AGENT_SEARCH_SUMMARY,
        render_agent_search_summary(search_evidence),
        args.check,
    )
    stale |= update(
        README, render_readme(readme, registry, conjectures), args.check
    )
    stale |= update(LEAN_CHECKS, render_lean(registry), args.check)
    stale |= update(
        STATE, render_state(state, registry, conjectures), args.check
    )
    if stale:
        raise SystemExit(1)


if __name__ == "__main__":
    # The documented workflow is edit-ledger, regenerate, gate — so this script
    # is the first thing a malformed ledger meets, before any validator has had
    # a chance to say what is wrong with it. A traceback here reports that the
    # generator broke; the validator reports which field did.
    try:
        main()
    except (AttributeError, TypeError, KeyError, IndexError) as error:
        print(
            f"generate_registry_views: the ledger is malformed ({error!r}).\n"
            "Run `python3 scripts/validate_registry.py` for the field and the "
            "reason.",
            file=sys.stderr,
        )
        raise SystemExit(1) from None
