#!/usr/bin/env python3
"""Generate current status and Lean declaration checks from registry data."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "registry.yaml"
LANDSCAPE = ROOT / "landscape.yaml"
SEARCH_EVIDENCE = ROOT / "docs/provenance/formalization-search.json"
STATUS = ROOT / "docs/status/formalization-status.md"
ATLAS_INDEX = ROOT / "docs/status/atlas-index.md"
LANDSCAPE_INDEX = ROOT / "docs/status/landscape-index.md"
PAPER_COVERAGE = ROOT / "docs/status/paper-coverage.md"
AGENT_BY_ID = ROOT / "docs/agent/by-id.json"
AGENT_SEARCH_SUMMARY = ROOT / "docs/agent/search-summary.json"
STATE = ROOT / "STATE.md"
README = ROOT / "README.md"
LEAN_CHECKS = ROOT / "AISafetyAtlas/Examples/Registry.lean"
README_START = "<!-- BEGIN GENERATED REGISTRY SCOPE -->"
README_END = "<!-- END GENERATED REGISTRY SCOPE -->"
STATE_START = "<!-- BEGIN GENERATED REGISTRY SNAPSHOT -->"
STATE_END = "<!-- END GENERATED REGISTRY SNAPSHOT -->"
COVERAGE_RELATIONSHIPS = {"EXACT", "EQUIVALENT"}
SEARCH_SUMMARY_MAX_PATHS = 3
def code_list(items: list[str]) -> str:
    return "<br>".join(f"`{item}`" for item in items)


def unique(items: list[str]) -> list[str]:
    return list(dict.fromkeys(items))


def has_reproduced_relationship(result: dict, relationships: set[str]) -> bool:
    return any(
        record["reproduced"] and record["relationship"] in relationships
        for record in result["formalizations"]
    )


def strongest_relationship(result: dict) -> str:
    reproduced = [
        record["relationship"]
        for record in result["formalizations"]
        if record["reproduced"]
    ]
    coverage = [r for r in reproduced if r in COVERAGE_RELATIONSHIPS]
    if coverage:
        return code_list(unique(coverage))
    if reproduced:
        return code_list(unique(reproduced))
    return "—"


def render_atlas_index(registry: dict) -> str:
    """One human-browsable row per surveyed result, generated from the registry so
    the full 44-row landscape is readable without parsing registry.yaml."""
    results = registry["results"]
    lines = [
        "<!-- Generated by scripts/generate_registry_views.py; do not edit directly. -->",
        "# Atlas Index",
        "",
        "One row per surveyed impossibility result, generated from",
        "[`registry.yaml`](../../registry.yaml). `Formalization` is the strongest",
        "reproduced relationship; `Bridge` is the AI-system interpretation review",
        "state; `Candidate` counts manually discovered leads not yet accepted as",
        "coverage. See [formalization status](formalization-status.md) for headline",
        "coverage counting and [open work](../guide/open-work.md) for next actions.",
        "",
        "| ID | Survey result | Informal claim | Formalization | Bridge | Candidate leads |",
        "|---|---|---|---|---|---:|",
    ]
    for result in results:
        claim = result["informal_claim"].replace("|", "\\|")
        leads = result.get("candidate_formalizations", [])
        candidate = str(len(leads)) if leads else "—"
        lines.append(
            f"| {result['id']} | {result['name']} | {claim} | "
            f"{strongest_relationship(result)} | `{result['ai_bridge_status']}` | {candidate} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_status(registry: dict, search_evidence: dict) -> str:
    results = registry["results"]
    covered = [
        result
        for result in results
        if has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS)
    ]
    related_only = [
        result
        for result in results
        if not has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS)
        and has_reproduced_relationship(result, {"RELATED"})
    ]
    formalizations = [
        record for result in results for record in result["formalizations"]
    ]
    artifacts = [
        declaration
        for result in results
        if result["lean_artifact"] is not None
        for declaration in result["lean_artifact"]["declarations"]
    ]
    bridges = [artifact for artifact in artifacts if artifact["type"] == "BRIDGE"]
    wrappers = [artifact for artifact in artifacts if artifact["type"] == "WRAPPER"]
    new_proofs = [artifact for artifact in artifacts if artifact["type"] == "NEW_PROOF"]
    references = [artifact for artifact in artifacts if artifact["type"] == "REFERENCE"]
    rows_with_bridge = sum(
        result["lean_artifact"] is not None
        and any(d["type"] == "BRIDGE" for d in result["lean_artifact"]["declarations"])
        for result in results
    )
    rows_wrapper_only = sum(
        result["lean_artifact"] is not None
        and all(d["type"] == "WRAPPER" for d in result["lean_artifact"]["declarations"])
        for result in results
    )
    candidate_leads = sum(
        len(result.get("candidate_formalizations") or []) for result in results
    )
    external = [
        (result, record)
        for result in results
        for record in result["formalizations"]
        if record["framework"] != "Lean" and record["reproduced"]
    ]
    reviewed_results = sum(
        result["ai_bridge_status"] != "HUMAN_REVIEW" for result in results
    )
    candidate_results = sum(
        any(hit["hit_count"] for hit in evidence["candidate_hits"].values())
        for evidence in search_evidence["results"].values()
    )

    lines = [
        "<!-- Generated by scripts/generate_registry_views.py; do not edit directly. -->",
        "# Formalization Status",
        "",
        "The machine-readable sources of truth are [`registry.yaml`](../../registry.yaml)",
        "and [`formalization-search.json`](../provenance/formalization-search.json). Adjacent",
        "non-survey formalizations live in [`landscape.yaml`](../../landscape.yaml) and",
        "do not affect the headline coverage count. Regenerate this page with",
        "`python3 scripts/generate_registry_views.py`.",
        "",
        "| Metric | Current |",
        "|---|---:|",
        f"| Survey results inventoried | {len(results)} / {registry['survey']['expected_result_count']} |",
        f"| Survey results with verified `EXACT`/`EQUIVALENT` formalizations | {len(covered)} |",
        f"| Additional survey results with `RELATED` formalizations only | {len(related_only)} |",
        f"| Verified formalization records | {len(formalizations)} |",
        f"| Atlas Lean theorem declarations | {len(artifacts)} across {sum(result['lean_artifact'] is not None for result in results)} survey results |",
        f"| … of which `WRAPPER` | {len(wrappers)} |",
        f"| … of which `BRIDGE` | {len(bridges)} |",
        f"| … of which `NEW_PROOF` | {len(new_proofs)} |",
        f"| … of which `REFERENCE` | {len(references)} |",
        f"| Survey rows whose atlas Lean is wrapper-only | {rows_wrapper_only} |",
        f"| Survey rows with at least one `BRIDGE` declaration | {rows_with_bridge} |",
        f"| Structured `candidate_formalizations` leads | {candidate_leads} |",
        f"| Reproduced external coverage records | {len(external)} across {len({result['id'] for result, _ in external})} survey results |",
        f"| Survey results with reviewed AI-system bridges | {reviewed_results} |",
        f"| Survey rows with six-corpus discovery evidence | {len(search_evidence['results'])} / {len(results)} |",
        "",
        "Headline formalization coverage counts a survey result only when it has a",
        "reproduced `EXACT` or `EQUIVALENT` record. That is a **map** metric (evidence",
        "exists), not a **research-density** metric: many covered rows expose only",
        "`WRAPPER` aliases over maintained upstream mathematics. A `RELATED` bridge",
        "remains visible but does not increase the headline count, especially while",
        "its interpretation is under `HUMAN_REVIEW`.",
        "",
        "## Atlas Lean declarations",
        "",
        "| ID | Survey result | Formalization relationships | Source declarations | Atlas declarations and layers |",
        "|---|---|---|---|---|",
    ]

    for result in results:
        artifact = result["lean_artifact"]
        if artifact is None:
            continue
        declarations = artifact["declarations"]
        sources = unique(
            [
                source
                for declaration in declarations
                for source in declaration["source_declarations"]
            ]
        )
        atlas = [
            f"{declaration['atlas_declaration']} ({declaration['type']})"
            for declaration in declarations
        ]
        relationships = unique(
            [record["relationship"] for record in result["formalizations"]]
        )
        lines.append(
            f"| {result['id']} | {result['name']} | {code_list(relationships)} | "
            f"{code_list(sources)} | {code_list(atlas)} |"
        )

    lines.extend(
        [
            "",
            "The generated declaration-presence checks live in",
            "[`AISafetyAtlas/Examples/Registry.lean`](../../AISafetyAtlas/Examples/Registry.lean).",
            "The hand-written `PublicAPI` examples separately protect the intended theorem",
            "signatures and root-import usability.",
            "",
            "## Reproduced external coverage",
            "",
            "| ID | Survey result | Framework | Declaration | Relationship | Reproduction command |",
            "|---|---|---|---|---|---|",
        ]
    )
    for result, record in external:
        lines.append(
            f"| {result['id']} | {result['name']} | {record['framework']} | "
            f"`{record['declaration']}` | {record['relationship']} | "
            f"`{record['build_command']}` |"
        )

    lines.extend(
        [
            "",
            "Additional reproduced variants and adjacent developments, including vNM",
            "expected utility, remain provenance rather than extra survey coverage; see",
            "[`external-formalizations.md`](../provenance/external-formalizations.md) and the",
            "[landscape index](landscape-index.md).",
            "",
            "## Discovery coverage",
            "",
            f"All {len(results)} rows have a **baseline classical six-corpus** search",
            "(Mathlib, Isabelle AFP, Rocq Undecidability, HOL4, HOL Light, Agda stdlib);",
            f"{candidate_results} rows produced raw candidate-file hits. That pass is",
            "**scoped** negative/positive evidence for those corpora only — it does not",
            "search third-party Lean packages (Foundation, KolmogorovMathlib, SocialChoiceLean,",
            "DASH, …). Manually discovered package leads use `candidate_formalizations` or",
            "[`landscape.yaml`](../../landscape.yaml). Candidate hits are discovery evidence,",
            "not verified formalizations. Relationship labels are",
            "`EXACT`, `EQUIVALENT`, `RELATED`, `DEPENDENCY_ONLY`, and `UNCLEAR`.",
            "An AI-safety interpretation remains `HUMAN_REVIEW` unless it has been",
            "separately defined and reviewed.",
            "",
        ]
    )
    return "\n".join(lines)


def _md_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _short_citation(citation: str, limit: int = 120) -> str:
    citation = " ".join(citation.split())
    if len(citation) <= limit:
        return citation
    return citation[: limit - 1] + "…"


def render_paper_coverage(registry: dict, landscape: dict) -> str:
    """Human table: source papers ↔ formalizations ↔ atlas surface (R coverage view)."""
    catalog = registry["source_catalog"]
    lines = [
        "<!-- Generated by scripts/generate_registry_views.py; do not edit directly. -->",
        "# Paper and formalization coverage",
        "",
        "One place to see **which source papers** the survey maps, **whether a",
        "machine-checked formalization exists**, and **where it lives** in the atlas.",
        "Generated from [`registry.yaml`](../../registry.yaml) and",
        "[`landscape.yaml`](../../landscape.yaml). Headline coverage still means",
        "reproduced `EXACT`/`EQUIVALENT` only; `RELATED` and landscape rows are listed",
        "but do not increase that count. See also [formalization status](formalization-status.md)",
        "and [atlas index](atlas-index.md).",
        "",
        "## Survey Table 1 results",
        "",
        "| ID | Result | Source paper(s) | Formalization (framework · relationship · declaration) | Atlas Lean | Bridge |",
        "|---|---|---|---|---|---|",
    ]
    for result in registry["results"]:
        refs = result.get("original_source_refs") or []
        if refs:
            papers = "<br>".join(
                _md_cell(_short_citation(catalog[ref]["citation"]))
                for ref in refs
                if ref in catalog
            )
            if not papers:
                papers = "—"
        else:
            papers = "—"

        forms = result.get("formalizations") or []
        if forms:
            form_cells = []
            for record in forms:
                decl = record.get("declaration") or "—"
                form_cells.append(
                    f"{record['framework']} · `{record['relationship']}` · `{decl}`"
                    + (" · reproduced" if record.get("reproduced") else " · not reproduced")
                )
            formalization = "<br>".join(form_cells)
        else:
            formalization = "— (mapped only)"

        if result.get("lean_artifact"):
            atlas = code_list(
                d["atlas_declaration"]
                for d in result["lean_artifact"]["declarations"]
            )
        else:
            atlas = "—"

        lines.append(
            f"| {result['id']} | {_md_cell(result['name'])} | {papers} | "
            f"{formalization} | {atlas} | `{result['ai_bridge_status']}` |"
        )

    lines.extend(
        [
            "",
            "## Landscape (non–Table-1)",
            "",
            "These are first-class provenance or public Lean surface **outside** the",
            "headline 44-row coverage count.",
            "",
            "| ID | Name | Framework | Declaration / atlas | Reproduction | Notes |",
            "|---|---|---|---|---|---|",
        ]
    )
    for entry in landscape.get("entries", []):
        decl = entry.get("atlas_declaration") or entry.get("declaration") or "—"
        if decl != "—":
            decl = f"`{decl}`"
        repro = entry.get("reproduction") or "—"
        if repro != "—":
            repro = f"`{repro}`"
        notes = _md_cell(entry.get("notes") or "—")
        lines.append(
            f"| {entry['id']} | {_md_cell(entry['name'])} | {entry['framework']} | "
            f"{decl} | {repro} | {notes} |"
        )

    lines.extend(
        [
            "",
            "## AI safety literature (how addressed)",
            "",
            "Literature-first coverage estimation (Melo-style packaging, robot ethics,",
            "etc.) lives in the hand map",
            "[`related-literature.md`](../guide/related-literature.md)—not theorem-first.",
            "Some rows also appear as survey BY IDs above; do not double-count headline",
            "EXACT/EQUIVALENT. Optional `LAND-*` / `atlas-ref-*` keys support packaging.",
            "",
            "Regenerate: `python3 scripts/generate_registry_views.py`.",
            "",
        ]
    )
    return "\n".join(lines)


def render_landscape_index(landscape: dict) -> str:
    lines = [
        "<!-- Generated by scripts/generate_registry_views.py; do not edit directly. -->",
        "# Landscape Index",
        "",
        "Non–Table-1 formalizations from [`landscape.yaml`](../../landscape.yaml).",
        "These **never** increase the survey headline `EXACT`/`EQUIVALENT` count.",
        "Narrative provenance remains in [`external-formalizations.md`](../provenance/external-formalizations.md).",
        "",
        "| ID | Name | Framework | Atlas declaration | Root import | Reproduction |",
        "|---|---|---|---|---|---|",
    ]
    for entry in landscape["entries"]:
        decl = entry.get("atlas_declaration") or entry.get("declaration") or "—"
        if decl != "—":
            decl = f"`{decl}`"
        root = "yes" if entry.get("root_import") else "no"
        repro = entry.get("reproduction") or "—"
        if repro != "—":
            repro = f"`{repro}`"
        lines.append(
            f"| {entry['id']} | {entry['name']} | {entry['framework']} | "
            f"{decl} | {root} | {repro} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_state_snapshot(registry: dict, landscape: dict) -> str:
    """Generated block embedded in STATE.md so hand counts cannot drift (R7-1)."""
    results = registry["results"]
    covered = sum(
        has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS) for result in results
    )
    related_only = sum(
        not has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS)
        and has_reproduced_relationship(result, {"RELATED"})
        for result in results
    )
    artifacts = [
        declaration
        for result in results
        if result["lean_artifact"] is not None
        for declaration in result["lean_artifact"]["declarations"]
    ]
    lean_rows = sum(result["lean_artifact"] is not None for result in results)
    bridges = sum(a["type"] == "BRIDGE" for a in artifacts)
    wrappers = sum(a["type"] == "WRAPPER" for a in artifacts)
    reviewed = sum(result["ai_bridge_status"] != "HUMAN_REVIEW" for result in results)
    candidates = sum(
        len(result.get("candidate_formalizations") or []) for result in results
    )
    lines = [
        STATE_START,
        "<!-- Generated by scripts/generate_registry_views.py; do not edit by hand. -->",
        f"- Registry snapshot: **{len(artifacts)}** atlas Lean theorem declarations across",
        f"  **{lean_rows}** survey results; headline `EXACT`/`EQUIVALENT` coverage",
        f"  **{covered} of {len(results)}**; RELATED-only **{related_only}**; reviewed",
        f"  AI-system bridges **{reviewed}**; declaration layers WRAPPER **{wrappers}** /",
        f"  BRIDGE **{bridges}**; structured candidate leads **{candidates}**; landscape",
        f"  entries **{len(landscape.get('entries', []))}** (see `landscape.yaml`).",
        STATE_END,
    ]
    return "\n".join(lines)


def render_state(state: str, registry: dict, landscape: dict) -> str:
    generated = render_state_snapshot(registry, landscape)
    start = state.find(STATE_START)
    end = state.find(STATE_END)
    if start < 0 or end < start:
        # Insert snapshot after the phase line / first blank block if markers missing.
        raise ValueError(
            "STATE.md generated-snapshot markers are missing or out of order; "
            f"expected {STATE_START!r} … {STATE_END!r}"
        )
    end += len(STATE_END)
    return state[:start] + generated + state[end:]


def render_readme(readme: str, registry: dict) -> str:
    results = registry["results"]
    covered = sum(
        has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS)
        for result in results
    )
    related_only = sum(
        not has_reproduced_relationship(result, COVERAGE_RELATIONSHIPS)
        and has_reproduced_relationship(result, {"RELATED"})
        for result in results
    )
    related_noun = "result" if related_only == 1 else "results"
    reviewed = sum(
        result["ai_bridge_status"] != "HUMAN_REVIEW" for result in results
    )
    generated = "\n".join(
        [
            README_START,
            f"The current registry has verified `EXACT` or `EQUIVALENT` formalization coverage for",
            f"**{covered} of {len(results)}** survey results. It records **{related_only} additional {related_noun} with a",
            "`RELATED` formalization only**, outside headline coverage, and",
            f"**{reviewed} survey results with reviewed AI-system bridges**. It provides",
            "infrastructure for further formalization; it does not claim complete formal",
            "coverage. See the current [formalization status](docs/status/formalization-status.md).",
            README_END,
        ]
    )
    start = readme.find(README_START)
    end = readme.find(README_END)
    if start < 0 or end < start:
        raise ValueError("README generated-scope markers are missing or out of order")
    end += len(README_END)
    return readme[:start] + generated + readme[end:]


def render_lean(registry: dict) -> str:
    declarations = [
        declaration["atlas_declaration"]
        for result in registry["results"]
        if result["lean_artifact"] is not None
        for declaration in result["lean_artifact"]["declarations"]
    ]
    lines = [
        "module",
        "",
        "import AISafetyAtlas",
        "",
        "/-! Generated by `scripts/generate_registry_views.py`; do not edit directly. -/",
        "",
    ]
    lines.extend(f"#check {declaration}" for declaration in declarations)
    lines.append("")
    return "\n".join(lines)


def compact_formalization(record: dict) -> dict:
    """Agent-facing formalization fields only (omit build logs / license prose)."""
    return {
        "framework": record.get("framework"),
        "relationship": record.get("relationship"),
        "reproduced": record.get("reproduced"),
        "declaration": record.get("declaration"),
        "module": record.get("module"),
        "repository": record.get("repository"),
        "version": record.get("version"),
    }


def compact_result(result: dict) -> dict:
    """Compact survey row for agent lookup without loading full registry.yaml."""
    lean = result.get("lean_artifact")
    lean_out = None
    if lean is not None:
        lean_out = {
            "declarations": [
                {
                    "atlas_declaration": declaration["atlas_declaration"],
                    "type": declaration["type"],
                }
                for declaration in lean.get("declarations") or []
            ]
        }
    return {
        "id": result["id"],
        "name": result["name"],
        "status": result["status"],
        "ai_bridge_status": result["ai_bridge_status"],
        "mechanism_category": result.get("mechanism_category"),
        "domain_category": result.get("domain_category"),
        "informal_claim": result["informal_claim"],
        "formalizations": [
            compact_formalization(record)
            for record in result.get("formalizations") or []
        ],
        "lean_artifact": lean_out,
        "candidate_count": len(result.get("candidate_formalizations") or []),
    }


def compact_landscape_entry(entry: dict) -> dict:
    return {
        "id": entry["id"],
        "name": entry["name"],
        "framework": entry.get("framework"),
        "atlas_declaration": entry.get("atlas_declaration"),
        "related_survey_ids": entry.get("related_survey_ids") or [],
        "module": entry.get("module"),
        "survey_coverage": entry.get("survey_coverage"),
    }


def render_agent_by_id(registry: dict, landscape: dict) -> str:
    """Compact BY-### / LAND-### index for agents (token-cheap vs full registry)."""
    payload = {
        "schema_version": 1,
        "generated_by": "scripts/generate_registry_views.py",
        "note": (
            "Compact agent lookup. Prefer this over registry.yaml / landscape.yaml. "
            "Open the full YAML only for a single id when notes or candidate "
            "formalization detail is required."
        ),
        "survey_result_count": len(registry["results"]),
        "landscape_entry_count": len(landscape.get("entries") or []),
        "results_by_id": {
            result["id"]: compact_result(result) for result in registry["results"]
        },
        "landscape_by_id": {
            entry["id"]: compact_landscape_entry(entry)
            for entry in landscape.get("entries") or []
        },
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def compact_search_result(record: dict) -> dict:
    """Keep queries and non-zero corpus hits only (drop empty zero matrices)."""
    hits: dict[str, dict] = {}
    for corpus, hit in (record.get("candidate_hits") or {}).items():
        count = int(hit.get("hit_count") or 0)
        if count <= 0:
            continue
        paths = list(hit.get("paths") or [])[:SEARCH_SUMMARY_MAX_PATHS]
        hits[corpus] = {
            "hit_count": count,
            "matched_queries": list(hit.get("matched_queries") or []),
            "paths": paths,
        }
    return {
        "queries": list(record.get("queries") or []),
        "hits": hits,
        "total_hit_count": sum(item["hit_count"] for item in hits.values()),
    }


def render_agent_search_summary(search_evidence: dict) -> str:
    """Token-cheap discovery summary; prefer over formalization-search.json."""
    results = search_evidence.get("results") or {}
    compact_results = {
        result_id: compact_search_result(record)
        for result_id, record in results.items()
    }
    with_hits = sum(
        1 for record in compact_results.values() if record["total_hit_count"] > 0
    )
    payload = {
        "schema_version": 1,
        "generated_by": "scripts/generate_registry_views.py",
        "note": (
            "Compact discovery summary. Prefer this over "
            "docs/provenance/formalization-search.json. Full path lists and "
            "per-query zero counts live only in the full evidence file."
        ),
        "searched_on": search_evidence.get("searched_on"),
        "corpora": list((search_evidence.get("corpora") or {}).keys()),
        "result_count": len(compact_results),
        "results_with_hits": with_hits,
        "results": compact_results,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
def update(path: Path, expected: str, check: bool) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if actual == expected:
        return False
    if check:
        print(
            f"generated file is out of date: {path.relative_to(ROOT)}",
            file=sys.stderr,
        )
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"updated {path.relative_to(ROOT)}")
    return False


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when generated files are stale",
    )
    args = parser.parse_args()

    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    landscape = json.loads(LANDSCAPE.read_text(encoding="utf-8"))
    search_evidence = json.loads(SEARCH_EVIDENCE.read_text(encoding="utf-8"))
    readme = README.read_text(encoding="utf-8")
    state = STATE.read_text(encoding="utf-8")

    stale = False
    stale |= update(STATUS, render_status(registry, search_evidence), args.check)
    stale |= update(ATLAS_INDEX, render_atlas_index(registry), args.check)
    stale |= update(LANDSCAPE_INDEX, render_landscape_index(landscape), args.check)
    stale |= update(PAPER_COVERAGE, render_paper_coverage(registry, landscape), args.check)
    stale |= update(
        AGENT_BY_ID, render_agent_by_id(registry, landscape), args.check
    )
    stale |= update(
        AGENT_SEARCH_SUMMARY,
        render_agent_search_summary(search_evidence),
        args.check,
    )
    stale |= update(README, render_readme(readme, registry), args.check)
    stale |= update(LEAN_CHECKS, render_lean(registry), args.check)
    stale |= update(STATE, render_state(state, registry, landscape), args.check)
    if stale:
        raise SystemExit(1)
if __name__ == "__main__":
    main()
