module

public import AISafetyAtlas.Causal.Corruption
public import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-!
# MAIS-O33: no positive corruption fraction is uniformly tolerable

The witness `Causal.Corruption`'s indistinguishability theorem consumes. The
mathematics is MAIS issue [#9](https://github.com/lionellevine/MAIS/issues/9)'s
— Svyatoslav Novikov (kumino), generated by OpenAI Codex, 2026-08-04, CC BY 4.0
— run at `δ = 1/2` rather than the `δ = 0` the note chose, and on
action-independent kernels rather than the note's one skewed row. Both changes
are recorded in `docs/provenance/mais-o33-statability.md`; both are admissible
instances of `prob:corruption`, and both remove a dependency.

## The instance

`𝐒 = Fin (m+2)`, `𝐀 = Fin 2`, `n = 101`, `δ = 1/2`. Then `|𝐀| ≥ 2`, `n > 1`,
and `(n−1)(1−δ) = 50 > 4`, so this is one of the instances print quantifies
over, and a single one suffices: *uniform* tolerability is a claim about every
instance at once.

## Why the kernels ignore the action

`env` puts mass `p` on state `0` and spreads `1−p` over the rest, whatever the
action. That is print's own action-independent class — the one its myopic
converse is stated over — and nothing in `prob:corruption` excludes it. It buys
one thing: `Causal.trajectoryLaw_congr` makes the trajectory law *the same
measure* for every policy, so a `(δ,n)`-bounded agent can be assembled by
choosing a near-optimal policy per (start state, goal) pair and splicing,
without a congruence lemma for `ProbabilityTheory.Kernel.traj` that Mathlib does
not state.

It is not a weakening of the problem. `thm:rabe` claims a `(δ,n)`-bounded agent
determines the kernel to within `√(2/50) ≈ 0.2` on *any* communicating instance,
these two are `0.8` apart, and the agents built here agree except on the
exceptional goals. So the informative pairs are exactly that doubly
exponentially small set — which is the whole point of `prob:corruption`, not an
artefact of the class.

## Why `δ = 1/2` and not print's `δ = 0`

At `δ = 0` the boundedness clause reads `P(τ ⊨ ψ | π, s₀) = ⨆_{π'} …`, so the
two agents would have to be *exactly* optimal at every pair, and the existence
of optimal policies for reachability objectives on a finite controlled Markov
process becomes unavoidable. Mathlib does not carry it. At any `δ > 0` ordinary
supremum approximation suffices (`Causal.exists_achieveProb_ge`), and
`δ = 1/2` still leaves `(n−1)(1−δ) = 50`, which both clears print's constraint
and keeps the two worlds outside each other's reconstruction balls.

Nothing here uses `sorry` or an added axiom.
-/

namespace AISafetyAtlas.Examples.Causal.O33Corruption

open AISafetyAtlas.Causal Finset
open scoped ENNReal

/-! ## The two environments -/

/-- The exogenous chain that puts mass `p` on state `0` and spreads the rest
uniformly. The action is never read, which is print's own action-independent
class. -/
@[expose] public noncomputable def env (m : ℕ) {p : ℝ} (hp0 : 0 ≤ p) (hp1 : p ≤ 1) :
    ControlledMarkovProcess (Fin (m + 2)) (Fin 2) where
  prob := fun _ _ s' ↦ if s' = 0 then p else (1 - p) / (m + 1)
  prob_nonneg := by
    intro s a s'
    by_cases h : s' = 0
    · simpa [h] using hp0
    · have : (0 : ℝ) < (m : ℝ) + 1 := by positivity
      simp only [h, if_false]
      exact div_nonneg (by linarith) this.le
  prob_sum := by
    intro s a
    classical
    rw [← Finset.sum_erase_add _ _ (Finset.mem_univ (0 : Fin (m + 2)))]
    have hrest : ∀ x ∈ (Finset.univ : Finset (Fin (m + 2))).erase 0,
        (if x = 0 then p else (1 - p) / (m + 1)) = (1 - p) / (m + 1) := fun x hx ↦
      if_neg (Finset.ne_of_mem_erase hx)
    rw [Finset.sum_congr rfl hrest, Finset.sum_const,
      Finset.card_erase_of_mem (Finset.mem_univ _), Finset.card_univ, Fintype.card_fin,
      if_pos rfl, nsmul_eq_mul]
    have hm : (0 : ℝ) < (m : ℝ) + 1 := by positivity
    have hcast : ((m + 2 - 1 : ℕ) : ℝ) = (m : ℝ) + 1 := by
      push_cast [Nat.add_sub_cancel]
      ring
    rw [hcast]
    field_simp
    ring

public theorem env_actionIndependent (m : ℕ) {p : ℝ} (hp0 : 0 ≤ p) (hp1 : p ≤ 1) :
    (env m hp0 hp1).ActionIndependent := fun _ _ _ _ ↦ rfl

public theorem env_communicating (m : ℕ) {p : ℝ} (hp0 : 0 ≤ p) (hp1 : p ≤ 1)
    (hp0' : 0 < p) (hp1' : p < 1) : (env m hp0 hp1).Communicating := by
  refine ControlledMarkovProcess.communicating_of_fullSupport ?_
  intro s a s'
  by_cases h : s' = 0
  · simpa [env, h] using hp0'
  · have hm : (0 : ℝ) < (m : ℝ) + 1 := by positivity
    simp only [env, h, if_false]
    exact div_pos (by linarith) hm

public theorem env_separated (m : ℕ) {p q : ℝ} (hp0 : 0 ≤ p) (hp1 : p ≤ 1)
    (hq0 : 0 ≤ q) (hq1 : q ≤ 1) :
    (env m hp0 hp1).SeparatedBy (env m hq0 hq1) |p - q| :=
  ⟨0, 0, 0, by simp [env]⟩

/-- The world that stays at state `0` nine times in ten. -/
@[expose] public noncomputable def envHi (m : ℕ) :
    ControlledMarkovProcess (Fin (m + 2)) (Fin 2) :=
  env m (p := 9 / 10) (by norm_num) (by norm_num)

/-- The world that leaves state `0` nine times in ten. -/
@[expose] public noncomputable def envLo (m : ℕ) :
    ControlledMarkovProcess (Fin (m + 2)) (Fin 2) :=
  env m (p := 1 / 10) (by norm_num) (by norm_num)

/-! ## The instance

`n = 101` and `δ = 1/2` clear print's `(n−1)(1−δ) > 4` with room: the product is
`50`, so the target radius is `2/√50` and the two worlds are `4/5` apart, which
is more than twice it. Print's `δ = 0` would force exact optimality on the two
agents and with it the optimal-policy-attainment theorem; `δ = 1/2` is
admissible and needs only supremum approximation. -/

/-- Print's depth for this instance. -/
@[expose] public def o33Depth : ℕ := 101

/-- Print's failure rate for this instance. -/
@[expose] public noncomputable def o33Delta : ℝ := 1 / 2

public theorem o33_admissible : 4 < ((o33Depth : ℝ) - 1) * (1 - o33Delta) := by
  norm_num [o33Depth, o33Delta]

public theorem o33_radius :
    2 * reconstructionRadius o33Depth o33Delta < |(9 / 10 : ℝ) - 1 / 10| := by
  have harg : ((o33Depth : ℝ) - 1) * (1 - o33Delta) = 50 := by
    norm_num [o33Depth, o33Delta]
  have h5 : (5 : ℝ) < Real.sqrt 50 := (Real.lt_sqrt (by norm_num)).mpr (by norm_num)
  have hval : 2 * reconstructionRadius o33Depth o33Delta = 4 / Real.sqrt 50 := by
    rw [reconstructionRadius, harg]
    ring
  rw [hval]
  have habs : |(9 / 10 : ℝ) - 1 / 10| = 4 / 5 := by
    rw [abs_of_nonneg (by norm_num)]
    norm_num
  rw [habs]
  exact div_lt_div_of_pos_left (by norm_num) (by norm_num) h5

public theorem envHi_actionIndependent (m : ℕ) : (envHi m).ActionIndependent :=
  fun _ _ _ _ ↦ rfl

public theorem envLo_actionIndependent (m : ℕ) : (envLo m).ActionIndependent :=
  fun _ _ _ _ ↦ rfl

public theorem envHi_communicating (m : ℕ) : (envHi m).Communicating :=
  env_communicating m _ _ (by norm_num) (by norm_num)

public theorem envLo_communicating (m : ℕ) : (envLo m).Communicating :=
  env_communicating m _ _ (by norm_num) (by norm_num)

public theorem envHi_separated (m : ℕ) :
    (envHi m).SeparatedBy (envLo m) |(9 / 10 : ℝ) - 1 / 10| :=
  env_separated m _ _ _ _

/-! ## The two agents, and the one corruption that serves both -/

/-- **No positive corruption fraction survives at this instance.** Two agents,
bounded in two worlds `4/5` apart, whose first-action maps differ only at the
(start state, goal) pairs carrying no immediate win — a doubly exponentially
small fraction. The honest map of one is an admissible corruption of the other,
so an analyst faces the same oracle in both worlds. -/
public theorem not_tolerantAt (m : ℕ) {η : ℝ}
    (hη : 2 / 2 ^ (2 ^ (Fintype.card (Fin (m + 2)) * Fintype.card (Fin 2) - 1)) ≤ η) :
    ¬ TolerantAt (Fin (m + 2)) (Fin 2) o33Depth o33Delta η := by
  have hδ : (0 : ℝ) < o33Delta := by norm_num [o33Delta]
  obtain ⟨π₀, hb₀, hf₀⟩ :=
    exists_isDeltaBounded_prescribing (envHi_actionIndependent m) o33Depth hδ (0 : Fin 2)
  obtain ⟨π₁, hb₁, hf₁⟩ :=
    exists_isDeltaBounded_prescribing (envLo_actionIndependent m) o33Depth hδ (0 : Fin 2)
  have hη0 : (0 : ℝ) ≤ η := le_trans (by positivity) hη
  refine not_tolerantAt_of_common_corruption (envHi_separated m) o33_radius
    (envHi_communicating m) (envLo_communicating m)
    (π₀ := fun Ψ ↦ liftPolicy (π₀ Ψ)) (π₁ := fun Ψ ↦ liftPolicy (π₁ Ψ))
    (isDeltaBoundedFull_lift_iff.mpr hb₀) (isDeltaBoundedFull_lift_iff.mpr hb₁)
    (ρ := firstActionMap π₁) ?_ (by
      rw [firstActionMapFull_lift]
      exact isCorruption_self hη0 _)
  rw [firstActionMapFull_lift]
  refine isCorruption_of_agree_off_avoiding (by norm_num [o33Depth]) (0 : Fin 2) _ _ ?_ hη
  intro s Ψ hΨ hnd
  rw [hf₁ s Ψ (fun hc ↦ hnd hc.2), hf₀ s Ψ (fun hc ↦ hnd hc.2)]

/-- **One instance per positive `η`.** The exceptional fraction is `2^{1−R}`
with `R = 2^{2|𝐒|−1}`, so raising the state count clears any budget. -/
public theorem exists_not_tolerantAt {η : ℝ} (hη : 0 < η) :
    ∃ m : ℕ, ¬ TolerantAt (Fin (m + 2)) (Fin 2) o33Depth o33Delta η := by
  obtain ⟨N, hN⟩ := exists_pow_lt_of_lt_one (show (0 : ℝ) < η / 2 by linarith)
    (show (1 : ℝ) / 2 < 1 by norm_num)
  refine ⟨N, not_tolerantAt N ?_⟩
  have hcard : Fintype.card (Fin (N + 2)) * Fintype.card (Fin 2) - 1 = 2 * N + 3 := by
    simp only [Fintype.card_fin]
    omega
  rw [hcard]
  have hNle : N ≤ 2 ^ (2 * N + 3) := le_trans (by omega) (Nat.le_of_lt (Nat.lt_two_pow_self))
  have hpow : (2 : ℝ) ^ N ≤ (2 : ℝ) ^ (2 ^ (2 * N + 3)) := by
    exact pow_le_pow_right₀ (by norm_num) hNle
  have hstep : (2 : ℝ) / 2 ^ (2 ^ (2 * N + 3)) ≤ 2 / 2 ^ N := by
    gcongr
  refine le_trans hstep ?_
  have hNpos : (0 : ℝ) < 2 ^ N := by positivity
  rw [one_div, inv_pow] at hN
  rw [div_le_iff₀ hNpos]
  have : (2 : ℝ) * ((2 : ℝ) ^ N)⁻¹ < η := by
    have := (mul_lt_mul_of_pos_left hN (by norm_num : (0:ℝ) < 2))
    linarith
  have h2 : (2 : ℝ) * ((2 : ℝ) ^ N)⁻¹ * 2 ^ N = 2 := by
    field_simp
  nlinarith [hNpos]

end AISafetyAtlas.Examples.Causal.O33Corruption
