"""Human-readable catalogue rendering for all catalogued sources."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote


def review_signal_links(source_id: str, rec: dict[str, Any]) -> list[str]:
    """Targeted links jumping directly to the source's row in source-review.md."""
    if not rec:
        return []
    status = rec.get("status")
    if status in {"NO_AUTOMATED_FOLLOWUP", "AUTOMATED_CLEAR"}:
        return [f"[No automated follow-up flagged](source-review.md#clear-{source_id})"]
    if status == "LOOKUP_FAILED":
        return [f"[Lookup error or retrieval gap](source-review.md#gap-{source_id})"]

    signals: list[str] = []
    if rec.get("notes") == "No locator is recorded in registry.yaml.":
        signals.append(f"[No locator recorded in registry](source-review.md#gap-{source_id})")

    if rec.get("related_dois"):
        signals.append(f"[Published journal DOI reported on arXiv](source-review.md#version-{source_id})")

    comparisons = rec.get("metadata", [])
    for c in comparisons:
        fld = c.get("field", "")
        outcome = c.get("outcome")
        if outcome == "POSSIBLE_CONFLICT":
            signals.append(f"[Potential {fld} difference](source-review.md#diff-{source_id}-{fld})")
        elif outcome == "MISSING_IN_CATALOGUE":
            signals.append(f"[{fld} not extracted from Atlas citation](source-review.md#missing-cat-{source_id}-{fld})")
        elif outcome == "MISSING_IN_SOURCE":
            signals.append(f"[Retrieved record did not expose {fld}](source-review.md#missing-src-{source_id}-{fld})")

    rights = rec.get("rights", {})
    if rights.get("outcome") == "NO_EXPLICIT_RIGHTS":
        signals.append(f"[No machine-readable license found](source-review.md#rights-{source_id})")

    if not signals:
        signals.append("[Pending review in source review](source-review.md)")

    return signals


def render_source_catalog(
    registry: dict[str, Any],
    review: dict[str, Any],
    conjectures: dict[str, Any],
) -> str:
    """A complete, human-readable record of every catalogued source.

    The canonical catalogue lives in `registry.yaml` under `source_catalog`, but
    raw JSON is inconvenient to read and link to directly. This generated view
    renders every recorded metadata field for each source (citation, locator,
    survey number, role, retrieved date, revision pin, content hash, and editorial notes),
    along with reverse-index links to citing results or conjectures and
    targeted links jumping directly to its specific rows in `source-review.md`.
    """
    catalogue = registry.get("source_catalog", {})
    records = review.get("records", {})

    citing_results: dict[str, list[tuple[str, str]]] = {}
    for result in registry.get("results", []):
        result_id = result.get("id", "")
        result_name = result.get("name", "")
        for ref in result.get("original_source_refs", []):
            citing_results.setdefault(ref, []).append((result_id, result_name))

    citing_conjectures: dict[str, list[dict[str, Any]]] = {}
    for conj in conjectures.get("conjectures", []):
        conj_id = conj.get("id", "")
        conj_name = conj.get("name", "")
        scope = conj.get("source_scope", "")
        fidelity = conj.get("source_fidelity", "")
        for ref in conj.get("source_ref", []):
            citing_conjectures.setdefault(ref, []).append(
                {
                    "id": conj_id,
                    "name": conj_name,
                    "role": "statement source",
                    "scope": scope,
                    "fidelity": fidelity,
                }
            )
        for ref in conj.get("context_source_ref", []):
            citing_conjectures.setdefault(ref, []).append(
                {
                    "id": conj_id,
                    "name": conj_name,
                    "role": "context source",
                    "scope": scope,
                    "fidelity": fidelity,
                }
            )

    works = [
        (source_id, source)
        for source_id, source in sorted(catalogue.items())
        if source.get("role") == "work"
    ]
    directories = [
        (source_id, source)
        for source_id, source in sorted(catalogue.items())
        if source.get("role") == "directory"
    ]

    lines = [
        "<!-- Generated by scripts/generate_registry_views.py; do not edit directly. -->",
        "# Source Catalog",
        "",
        f"Complete human-readable catalogue of all **{len(catalogue)}** entries in "
        f"[`registry.yaml`](../../../registry.yaml) (**{len(works)}** works and "
        f"**{len(directories)}** directories). Every bibliographic citation, locator, "
        "provenance hash, survey index, editorial note, citing atlas result or conjecture, and "
        "audit review signal is recorded below.",
        "",
        "For the metadata and rights audit comparison, see "
        "[`source-review.md`](source-review.md). "
        "For the high-level index of source reports, see [`README.md`](README.md).",
        "",
        "## Catalogued works",
        "",
    ]

    def render_source_entry(source_id: str, source: dict[str, Any]) -> list[str]:
        entry = [
            f'<a id="{source_id}"></a>',
            f"### `{source_id}`",
            "",
            f"- **Citation:** {source.get('citation') or '—'}",
            f"- **Role:** `{source.get('role') or '—'}`",
        ]
        if "survey_number" in source:
            entry.append(
                f"- **Survey index:** Ref. #{source['survey_number']} in Brcic & Yampolskiy (2023)"
            )
        locator = source.get("locator")
        if locator:
            entry.append(f"- **Locator:** [{locator}](<{quote(locator, safe=':/?&=#%')}>)")
        else:
            entry.append("- **Locator:** —")
        if source.get("retrieved"):
            entry.append(f"- **Retrieved:** `{source['retrieved']}`")
        if source.get("revision"):
            entry.append(f"- **Revision:** `{source['revision']}`")
        if source.get("content_sha256"):
            entry.append(f"- **Content SHA-256:** `{source['content_sha256']}`")
        if source.get("license"):
            entry.append(f"- **License:** {source['license']}")
        if source.get("rights"):
            entry.append(f"- **Rights:** {source['rights']}")
        if source.get("notes"):
            entry.append(f"- **Atlas notes:** {source['notes']}")

        c_results = citing_results.get(source_id, [])
        c_conjs = citing_conjectures.get(source_id, [])
        if c_results or c_conjs:
            refs = []
            for rid, rname in c_results:
                refs.append(f"[`{rid}`](../formalization-status.md) (*{rname}*)")
            for c_info in c_conjs:
                cid = c_info["id"]
                cname = c_info["name"]
                details = [c_info["role"]]
                if c_info["scope"]:
                    details.append(f"scope `{c_info['scope']}`")
                if c_info["fidelity"]:
                    details.append(f"fidelity `{c_info['fidelity']}`")
                detail_str = ", ".join(details)
                label = f" (*{cname}*, {detail_str})" if cname else f" ({detail_str})"
                refs.append(f"[`{cid}`](../../guide/conjectures.md){label}")
            entry.append(f"- **Cited in Atlas:** {'; '.join(refs)}")
        else:
            entry.append(
                "- **Cited in Atlas:** (Catalogue entry only; not directly cited on a claim or conjecture row)"
            )

        signals = review_signal_links(source_id, records.get(source_id, {}))
        if signals:
            entry.append(f"- **Audit check:** {'; '.join(signals)}")

        entry.append("")
        return entry

    for source_id, source in works:
        lines.extend(render_source_entry(source_id, source))

    lines.extend([
        "## Catalogued directories",
        "",
    ])
    for source_id, source in directories:
        lines.extend(render_source_entry(source_id, source))

    return "\n".join(lines)
