-- Generated by scripts/generate_registry_views.py; do not edit directly.
module

public import AISafetyAtlas.Causal.EffectiveGenericity
public import AISafetyAtlas.Conjectures.MAIS
public import AISafetyAtlas.Conjectures.MAIS.O27
public import AISafetyAtlas.Conjectures.MAIS.O31
public import AISafetyAtlas.Conjectures.MAIS.O38
public import AISafetyAtlas.Conjectures.StochasticComplexity

/-!
# Conjecture statement checks

Every Lean name recorded in `conjectures.yaml`, checked against what
its row claims it is. A row of kind *claim* or *answer* names a
doubted proposition, so `example : Prop := name` holds it to being
closed and `Prop`-valued -- `#check` would only print whatever type it
happens to have. A row of kind *target* names a **specification**,
whose type is deliberately not `Prop`: a candidate type, a quantity, a
predicate over a candidate answer. There `#check` is the right
strength, because what is being asserted is that the declaration
exists. A row of kind *blocked* names nothing, and its recorded
absences are checked the other way round, by
`scripts/check_cited_declarations.py`.

Nothing here is proved, and this module is not on the atlas root import.
-/

-- CONJ-002 (claim, OPEN)
example : Prop := AISafetyAtlas.Conjectures.StochasticComplexity.eq_needs_no_null_points

-- CONJ-003 (claim, RESOLVED)
example : Prop := AISafetyAtlas.Conjectures.MAIS.maisO26_exactRate

-- CONJ-004 (claim, RESOLVED)
example : Prop := AISafetyAtlas.Conjectures.MAIS.maisO23_marginsDoNotSuffice

-- CONJ-005 (claim, RESOLVED)
example : Prop := AISafetyAtlas.Conjectures.MAIS.maisO34_marginAloneDoesNotIdentify

-- CONJ-006 (claim, OPEN)
example : Prop := AISafetyAtlas.Conjectures.MAIS.maisO25_exactQueryRate

-- CONJ-008 (claim, RESOLVED)
example : Prop := AISafetyAtlas.Conjectures.MAIS.maisO29_boltzmannNotInjective

-- CONJ-009 (answer, RESOLVED)
example : Prop := AISafetyAtlas.Conjectures.MAIS.maisO34_exactFiberCandidate
#check @AISafetyAtlas.Conjectures.MAIS.maisO34_exactFiberCandidate

-- CONJ-010 (answer, OPEN)
example : Prop := AISafetyAtlas.Conjectures.MAIS.maisO31_chainClassificationCandidate
#check @AISafetyAtlas.Conjectures.MAIS.maisO31_chainClassificationCandidate

-- CONJ-012 (target, RESOLVED)
#check @AISafetyAtlas.Causal.O24Solution
#check @AISafetyAtlas.Causal.O24Constructor
#check @AISafetyAtlas.Causal.O24Solution

-- CONJ-013 (target, OPEN)
#check @AISafetyAtlas.Conjectures.MAIS.IsO27RadiusVanishingCriterion
#check @AISafetyAtlas.Conjectures.MAIS.IsO27RadiusVanishingCriterion
#check @AISafetyAtlas.Conjectures.MAIS.IsO27FirstOrderConstantFunction
#check @AISafetyAtlas.Conjectures.MAIS.IsO27EdgeSurvivalRegion

-- CONJ-016 (target, OPEN)
#check @AISafetyAtlas.Conjectures.MAIS.boltzmannMinimaxRisk
#check @AISafetyAtlas.Conjectures.MAIS.IsBoltzmannRiskRate

-- CONJ-017 (target, OPEN)
#check @AISafetyAtlas.Conjectures.MAIS.IsO31IdentifiableSetAlmostEverywhere
#check @AISafetyAtlas.Conjectures.MAIS.IsO31IdentifiableSetAlmostEverywhere

-- CONJ-018 (blocked, OPEN)
-- No Lean declaration: AISafetyAtlas.Causal.SampledActionOracle, AISafetyAtlas.Causal.CorruptedAnswer are recorded absent.

-- CONJ-019 (blocked, OPEN)
-- No Lean declaration: AISafetyAtlas.Causal.AverageAdmissibleFamily, AISafetyAtlas.Causal.profilePairMeasure are recorded absent.

-- CONJ-020 (blocked, OPEN)
-- No Lean declaration: AISafetyAtlas.Conjectures.MAIS.boltzmannMinimaxRiskUnder, AISafetyAtlas.Conjectures.MAIS.IsOptimalQueryDesign are recorded absent.

-- CONJ-021 (blocked, OPEN)
-- No Lean declaration: AISafetyAtlas.Causal.RestrictedMixture, AISafetyAtlas.Causal.SigmaIdentifiable are recorded absent.

-- CONJ-022 (blocked, OPEN)
-- No Lean declaration: AISafetyAtlas.Causal.ControlledMarkovProcess, AISafetyAtlas.Causal.FirstActionFamily, AISafetyAtlas.Causal.resolutionRadius are recorded absent.

-- CONJ-023 (blocked, OPEN)
-- No Lean declaration: AISafetyAtlas.Causal.PersistentAdversary, AISafetyAtlas.Causal.succeedsWithProbability are recorded absent.

-- CONJ-024 (blocked, OPEN)
-- No Lean declaration: AISafetyAtlas.Causal.sampledActionBudget, AISafetyAtlas.Causal.SwitchingSurface are recorded absent.

-- CONJ-025 (claim, RESOLVED)
example : Prop := AISafetyAtlas.Conjectures.MAIS.maisO38_polynomialSamplesSuffice
#check @AISafetyAtlas.Conjectures.MAIS.o38PolynomialSampleCandidate
