-- Generated by scripts/generate_registry_views.py; do not edit directly.
module

public import AISafetyAtlas.Conjectures.StochasticComplexity

/-!
# Conjecture statement checks

Every Lean name recorded in `conjectures.yaml`, required to be a closed
proposition. `example : Prop := name` fails unless the declaration is
`Prop`-valued; defining a proposition asserts nothing about its truth.
Nothing here is proved, and this module is not on the atlas root import.
-/

-- CONJ-002 (OPEN)
example : Prop := AISafetyAtlas.Conjectures.StochasticComplexity.eq_needs_no_null_points
